// -----------------------------------------------------------------------------
// Copyright (c) 2026 David B. Foster. All rights reserved.
// Contact: wizeman555@gmail.com
// Unauthorized copying, distribution, modification, or use of this file, in
// whole or in part, is strictly prohibited without the express written
// permission of the copyright holder.
// -----------------------------------------------------------------------------

//! The Swift <-> Rust boundary for FLOWS, and nothing else.
//!
//! Every function here is a thin, safe forwarder into `flows-core`: it
//! converts boundary representations, validates what arrived from Swift, and
//! contains panics. No domain logic lives here — that is `flows-core`'s job —
//! so the surface Swift sees stays smaller than the Rust API behind it
//! (3.25.5).
//!
//! # Unsafe
//!
//! No project-authored `unsafe` exists in this crate, and `forbid` enforces
//! that. The raw-pointer glue Swift calls through is generated by the pinned
//! `swift-bridge` macro; see `Cargo.toml` for why that is the standard's
//! prescribed shape and what it means for the lint.
//!
//! # Two rules the generated glue imposes on every Swift caller
//!
//! Read from swift-bridge 0.1.59's own source, because once we depend on it
//! its soundness is ours to establish (3.23, 3.25.8):
//!
//! - **Never pass an empty buffer.** `FfiSlice::as_slice` hands its pointer
//!   to `slice::from_raw_parts` without a null check, and Swift passes an
//!   empty array's buffer with a nil base address — undefined behaviour in
//!   Rust even at length zero. Every Swift facade returns the empty answer
//!   before crossing (RiskEquations.swift, FlowsCore.swift).
//! - **`&str` arguments must be valid UTF-8.** `RustStr::to_str` panics
//!   otherwise, inside the generated function, before [`contain`] can catch
//!   it. A Swift `String` is always valid UTF-8, so pass a `String` for every
//!   `&str`, never raw bytes.
//!
//! # Panics never cross the boundary
//!
//! Unwinding out of an `extern "C"` function aborts the process — a crash
//! mid-drive. Every exported function runs through [`contain`], which turns a
//! panic into a documented fallback value. By construction none of the
//! current functions can panic (no unchecked indexing, no integer arithmetic
//! that can overflow, lengths validated first); the containment is there so a
//! future edit that introduces one degrades to a visible fallback instead.
//!
//! # Threading
//!
//! Every function is a pure transform over its arguments with no shared or
//! global state, so any thread may call any of them concurrently. None
//! requires the main thread; none calls back into Swift.

#![forbid(unsafe_code)]

pub mod alerts;
pub mod climate;
pub mod geo;
pub mod learning;
pub mod places_text;
pub mod risk;
pub mod seasonal;
pub mod trip_vehicle;
pub mod vehicle_policy;

/// Run `f`, turning a panic into `fallback`.
pub(crate) fn contain<T>(fallback: T, f: impl FnOnce() -> T) -> T {
    std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)).unwrap_or(fallback)
}

#[cfg(test)]
mod tests {
    #[test]
    fn a_panic_becomes_the_fallback_instead_of_unwinding() {
        let hook = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));
        let v = super::contain(-1i32, || panic!("boom"));
        std::panic::set_hook(hook);
        assert_eq!(v, -1);
        assert_eq!(super::contain(-1i32, || 7), 7);
    }
}
