// -----------------------------------------------------------------------------
// Copyright (c) 2026 David B. Foster. All rights reserved.
// Contact: wizeman555@gmail.com
// Unauthorized copying, distribution, modification, or use of this file, in
// whole or in part, is strictly prohibited without the express written
// permission of the copyright holder.
// -----------------------------------------------------------------------------

import Foundation

/// EXACT ports of the FLOWS R server's risk equations — each function cites
/// its R source and is locked to R-computed vectors in FLOWSTests
/// (RiskEquationVectors.swift, generated BY the R functions themselves).
/// These make the app's risk math the R engine's risk math anywhere NWS
/// forecast data exists, instead of only where pre-scored ZIP exports reach.
enum RiskEquations {

    // MARK: R/scoring.R piecewise_score (line 244)

    /// 0 below `low`; linear GREEN_MIN→YELLOW_MIN across [low, medium];
    /// YELLOW_MIN→RED_MIN across (medium, high]; RED_MIN→1 above, slope
    /// (value−high)/high, capped at 1.
    static func piecewiseScore(_ value: Double, low: Double, medium: Double, high: Double) -> Double {
        let gMin = FlowsCore.riskGreenMin
        let yMin = FlowsCore.riskYellowMin
        let rMin = 0.8751   // RISK_RED_MIN
        if !value.isFinite || value <= 0 { return 0 }
        if value <= low { return 0 }
        if value <= medium {
            return gMin + (yMin - gMin) * ((value - low) / max(medium - low, 1e-9))
        }
        if value <= high {
            return yMin + (rMin - yMin) * ((value - medium) / max(high - medium, 1e-9))
        }
        return min(1, rMin + (1 - rMin) * ((value - high) / max(high, 1e-9)))
    }

    // MARK: R/scoring.R temperature_risk (line 279)

    /// 0 inside the comfort band; linear toward the record extremes, capped.
    static func temperatureRisk(
        tempF: Double, comfortLowF: Double, comfortHighF: Double,
        recordLowF: Double, recordHighF: Double
    ) -> Double {
        if !tempF.isFinite { return 0 }
        if tempF >= comfortLowF && tempF <= comfortHighF { return 0 }
        if tempF < comfortLowF {
            return min(1, (comfortLowF - tempF) / max(comfortLowF - recordLowF, 1e-9))
        }
        return min(1, (tempF - comfortHighF) / max(recordHighF - comfortHighF, 1e-9))
    }

    /// Is a temperature an UNUSUAL deviation for this climate — outside one
    /// standard deviation of local norms? The climate envelope gives comfort
    /// and record bounds; with the record ≈ the tail of the local distribution,
    /// σ ≈ (record − comfort)/3 per side. Used to GATE MAP PRESENTATION only
    /// (heat/cold badges and tints): a mildly-warm day scores small risk but
    /// isn't noteworthy enough to draw. The risk equations themselves are
    /// unchanged (R parity).
    static func temperatureAnomalous(
        tempF: Double, comfortLowF: Double, comfortHighF: Double,
        recordLowF: Double, recordHighF: Double
    ) -> Bool {
        guard tempF.isFinite else { return false }
        if tempF > comfortHighF {
            let sigma = max((recordHighF - comfortHighF) / 3, 1e-9)
            return tempF - comfortHighF > sigma
        }
        if tempF < comfortLowF {
            let sigma = max((comfortLowF - recordLowF) / 3, 1e-9)
            return comfortLowF - tempF > sigma
        }
        return false
    }

    // MARK: R/forecast.R:226–228 — the canonical forecast thresholds/weights

    static func windRisk(mph: Double) -> Double { piecewiseScore(mph, low: 15, medium: 28, high: 45) }
    static func popRisk(pct: Double) -> Double { piecewiseScore(pct, low: 25, medium: 50, high: 75) }

    /// forecast_score = min(1, 0.45·temp + 0.30·wind + 0.25·pop)  (R exact)
    static func forecastComposite(temp: Double, wind: Double, pop: Double) -> Double {
        min(1, 0.45 * temp + 0.30 * wind + 0.25 * pop)
    }

    // MARK: R/families.R environmental_family_weights (line 471) — exact

    static let familyWeights: [String: Double] = [
        "wind": 0.64, "flood": 0.96, "winter": 0.88, "convective": 0.92,
        "fire": 0.74, "heat": 0.70, "cold": 0.66, "air": 0.60,
        "radiation": 0.52, "seismic": 0.78,
        // `qpf_flood` is the app's key for the flood family; `flood` is the
        // R-export name. Alias so noisyOr resolves the same 0.96 either way.
        "qpf_flood": 0.96,
        // Live-feed acute hazards (not in the R export). Weighted by their
        // threat to life while driving: a tsunami/flood you cannot outrun in
        // a vehicle rank highest; UV/space-weather lowest.
        "tsunami": 0.97, "tropical": 0.94, "volcanic": 0.90, "avalanche": 0.86,
        // Precipitation PROBABILITY — a predictor of flood/storm/winter, not a
        // realized hazard. Moderate predictor weight so it advises/amplifies
        // without dominating the secondary combine.
        "precip": 0.55,
    ]

    // MARK: R/families.R noisy_or_combine (line 497) — exact shape

    /// 1 − Π(1 − wᵢ·clamp(sᵢ)) over (family, score) pairs.
    static func noisyOr(_ scores: [(family: String, score: Double)]) -> Double {
        var keep = 1.0
        for (family, raw) in scores {
            let s = raw.isFinite ? min(max(raw, 0), 1) : 0
            let w = min(max(familyWeights[family] ?? 1, 0), 1)
            keep *= 1 - w * s
        }
        return 1 - keep
    }

    // MARK: primary vs. secondary realization model

    /// Families that are directly life-threatening WHILE DRIVING and backed by
    /// PROOF — an OBSERVED event/detection or a reported road closure, never a
    /// forecast. Only a realized one can drive the band to Red. The test is
    /// TRAVEL SAFETY: the road is impassable (water over the road, a gauge in
    /// flood, the ground moved, a closure) or the driver is in direct danger
    /// passing through (in the fire — smoke/oxygen deprivation, heat, fallen
    /// trees; a tsunami you can't outrun; an erupting volcano). Every
    /// forecast/outlook/warning lives in `secondaryFamilies`.
    /// `storm` = a REALIZED severe/tornadic storm (an NWS Tornado / Severe
    /// Thunderstorm WARNING — happening/imminent-confirmed), distinct from the
    /// SPC `convective` OUTLOOK (a probability), which stays a predictor.
    /// `closure` = a DOT-reported road closure (WZDx all-lanes-closed) — the
    /// literal "proof of blocked road" primary: uncleared snow, washouts, and
    /// slides band Red the moment the state DOT reports the closure.
    static let primaryFamilies: Set<String> = [
        "fire", "qpf_flood", "flood", "storm", "closure",
        "seismic", "tsunami", "tropical", "volcanic",
    ]

    /// PREDICTOR / amplifier families — conditions or FORECASTS that raise the
    /// likelihood or severity of a realized primary but are NOT proof of a
    /// blocked road or an in-progress danger: high wind, heat, cold, haze/smoke,
    /// UV/space radiation, precipitation PROBABILITY, a FORECAST of winter (snow
    /// predicted, not a blocked road), the SPC severe-weather OUTLOOK
    /// (`convective` — a probability, not a tornado on the road), and the
    /// avalanche DANGER RATING (`avalanche` — a forecast, not an avalanche).
    /// They spike a realized primary; alone they only advise (capped below Red).
    /// Each realized form (a Tornado/Flash-Flood/Tsunami Warning, an avalanche or
    /// snow road closure) becomes a primary the moment that proof feed is wired.
    static let secondaryFamilies: Set<String> = [
        "wind", "heat", "cold", "air", "radiation", "precip", "winter",
        "convective", "avalanche",
    ]

    /// Upper-Yellow ceiling for a secondary-only situation: a pile of
    /// predictors (extreme fire-weather with no fire, high UV, haze, a windy
    /// clear day) can warn strongly but never reads life-threatening without a
    /// realized primary. Structurally below RISK_RED_MIN (0.8751).
    static let secondaryCeiling = 0.80

    /// Compounded, REALIZED risk from a family→score map — the total the
    /// Green/Yellow/Red band cuts are meant to sit on, honoring the
    /// primary/secondary structure:
    ///   • primaries combine by unweighted noisy-OR, so a realized primary
    ///     keeps its full severity and two independent primaries compound;
    ///   • secondaries (weighted noisy-OR = the R engine's combine) AMPLIFY the
    ///     realized primary — scaled by how realized it is, so no primary ⇒ no
    ///     amplification;
    ///   • secondaries alone yield only a capped advisory (never Red);
    ///   • total = max(amplified primary, capped secondary advisory).
    /// So several small or overlapping risks can never sum to a life-threatening
    /// total — Red requires a realized primary. Families outside both sets
    /// (e.g. the derived `environmental` composite) are ignored to avoid
    /// double-counting the temp/wind/pop signals their constituents already hold.
    static func realizedRisk(_ families: [String: Double]) -> Double {
        func clamp(_ x: Double) -> Double { x.isFinite ? min(max(x, 0), 1) : 0 }
        // One pass, no intermediate collections: this runs per corridor
        // sample per route (and per progress tick while scoring) — the old
        // filter+map into noisyOr allocated a Dictionary and an Array of
        // String tuples per call. Both products accumulate in the SAME
        // dictionary-iteration order the two-pass form used, so results are
        // bit-identical.
        var keep = 1.0            // primaries: a maxed primary stays maxed (weight 1)
        var secondaryKeep = 1.0   // predictors: weighted noisy-OR (R combine shape)
        for (f, s) in families {
            if primaryFamilies.contains(f) {
                keep *= 1 - clamp(s)
            } else if secondaryFamilies.contains(f) {
                let w = min(max(familyWeights[f] ?? 1, 0), 1)
                secondaryKeep *= 1 - w * clamp(s)
            }
        }
        let primaryBase = 1 - keep
        let secondary = 1 - secondaryKeep
        // Predictors spike a realized primary (∝ primaryBase → 0 with no primary).
        let primaryAmplified = primaryBase * (1 + (1 - primaryBase) * secondary)
        // Secondaries alone: a capped advisory, never Red.
        let secondaryAdvisory = min(secondaryCeiling, secondary)
        return max(primaryAmplified, secondaryAdvisory)
    }

    /// WATERLINE-THRESHOLD flood amplifier (multiplier ≥ 1 on the precip
    /// PREDICTOR — never proof; the realized primary stays the gauge/warning/
    /// closure). Water pools toward the LOCAL minimum and rises by the rain
    /// depth, so the physics is a threshold, not a linear ramp:
    ///
    ///   waterline = localMin + rainDepth   (rain accumulates at the low point)
    ///   headroom  = roadElevation − localMin   (how far the road sits above it)
    ///
    /// • headroom ≤ rainDepth → the risen waterline REACHES the road: a physical
    ///   flood crossing, amplified regardless of other evidence (1.6…2.0×).
    /// • headroom > rainDepth → the road is above the pooling water. Between the
    ///   local min and the road there is NO guarantee of flooding — the user's
    ///   rule — so it gets a bump ONLY with SUPPORTING EVIDENCE that water
    ///   reaches it (a FEMA A/V flood zone, a river gauge at/above flood stage,
    ///   or a mapped river/lake nearby), tapered by how close the waterline
    ///   comes. No evidence → 1.0 (no elevation-driven flood bump).
    ///
    /// Units: `qpfInches` is inches, elevations are meters → rain is converted
    /// (× 0.0254) so the inch-vs-meter comparison is real, not dodged.
    /// `localMinElevation` MUST be a WINDOWED local minimum (the nearby pooling
    /// low), not the whole corridor's global low hundreds of km away.
    static func floodElevationMultiplier(
        sampleElevation: Double?, localMinElevation: Double?,
        qpfInches: Double?, supportingEvidence: Double = 0
    ) -> Double {
        guard let qpf = qpfInches, qpf.isFinite, qpf > 0 else { return 1 }
        let rainMeters = qpf * 0.0254
        let evidence = min(max(supportingEvidence, 0), 1)
        guard let e = sampleElevation, let lo = localMinElevation,
              e.isFinite, lo.isFinite else {
            // No elevation data: rain matters only where there's water evidence.
            return 1 + 0.5 * evidence * min(qpf / 2, 1)
        }
        let headroom = max(e - lo, 0)          // meters above the local pooling low
        if headroom <= rainMeters {            // waterline reaches the road
            let submerge = min((rainMeters - headroom) / max(rainMeters, 0.01), 1)
            return 1 + (0.6 + 0.4 * submerge)  // 1.6 … 2.0
        }
        // Above the waterline: between local min and road, water pools LOWER —
        // flood only with evidence it reaches this road, tapered by proximity.
        guard evidence > 0 else { return 1 }
        let proximity = max(0, 1 - (headroom - rainMeters) / max(rainMeters, 0.01))
        return 1 + 0.5 * evidence * proximity
    }

    /// Balance the two truths for ROUTE ORDERING (never the display band): the
    /// realized-risk `band` (alerts + current conditions) and the IDENTIFIED ZIP
    /// exposure (the modeled field, then the on-device seasonal prior). A ZIP can
    /// carry known risk before any alert, and an alert can fire without prior ZIP
    /// risk — both are evidence. Identified risk is discounted (×0.6) relative to
    /// a realized hazard, so a realized Red still dominates; but between two
    /// same-band routes the one through lower-identified-risk ZIPs ranks safer.
    /// As the seasonal prior for THIS route/week accrues `priorConfidence`, it
    /// takes over from the static field. Noisy-OR so neither truth is erased.
    static func rankingRisk(band: Double, zipExposure: Double,
                            seasonalPrior: Double = 0, priorConfidence: Double = 0) -> Double {
        let z = min(max(zipExposure, 0), 1)
        let p = min(max(seasonalPrior, 0), 1)
        let c = min(max(priorConfidence, 0), 1)
        let identified = z * (1 - c) + p * c
        return 1 - (1 - min(max(band, 0), 1)) * (1 - 0.6 * identified)
    }

    /// Classify an NWS alert EVENT name into the `realizedRisk` family it feeds.
    /// The family's set membership (primary vs secondary) then decides whether it
    /// can reach Red: an in-progress-danger WARNING maps to a PRIMARY family
    /// (`storm`/`qpf_flood`/`tsunami`/`tropical`/`volcanic`), while a watch,
    /// advisory, or condition warning (Winter Storm, High Wind, Red Flag, Flood
    /// Watch, SPC-style thunderstorm watch) maps to a PREDICTOR family — capped,
    /// never Red on a forecast alone. Returns nil for events with no mapping.
    /// Order matters: the specific realized phrases are tested before the generic
    /// family words they contain. Shared by the route scorer and live corridor
    /// monitor so they band alerts exactly as the map does.
    static func alertFamily(_ event: String) -> String? {
        let e = event.lowercased()
        // --- realized, in-progress danger → PRIMARY family ---
        if e.contains("tornado warning") || e.contains("severe thunderstorm warning") { return "storm" }
        // Short-fused realized WARNINGS whose name embeds a generic season/
        // condition word — test them BEFORE the predictor substrings below, or
        // they silently downgrade to a capped secondary and can never reach Red.
        // Snow Squall Warning = radar-confirmed whiteout / flash-freeze occurring;
        // Dust/Blowing Dust Storm Warning = observed zero-visibility (I-10 pileups).
        if e.contains("snow squall warning") { return "storm" }
        if e.contains("dust storm warning") || e.contains("blowing dust warning") { return "storm" }
        // Fire WARNING (NWS FRW: an active wildfire threatening a populated area)
        // is realized → primary. But "fire weather warning" / "red flag" is a
        // hot-dry PREDICTOR — exclude it here (handled below).
        if e.contains("fire warning"), !e.contains("fire weather") { return "fire" }
        if e.contains("flash flood warning") || e.contains("flash flood emergency")
            || e.contains("flood warning") { return "qpf_flood" }
        if e.contains("tsunami warning") { return "tsunami" }
        if e.contains("hurricane warning") || e.contains("storm surge warning")
            || e.contains("extreme wind") || e.contains("tropical storm warning") { return "tropical" }
        // Only the realized forms are primary — an Ashfall ADVISORY (trace
        // ash) is a condition advisory and must stay Red-incapable (air).
        if e.contains("ashfall") || e.contains("volcano") {
            return e.contains("advisory") ? "air" : "volcanic"
        }
        // --- predictors (watch / advisory / condition warning) → SECONDARY ---
        if e.contains("winter") || e.contains("ice storm") || e.contains("blizzard")
            || e.contains("snow") || e.contains("freezing rain") { return "winter" }
        if e.contains("heat") { return "heat" }
        if e.contains("chill") || e.contains("freeze") || e.contains("frost")
            || e.contains("cold") { return "cold" }
        if e.contains("red flag") || e.contains("fire weather") { return "heat" }  // hot/dry fire-weather
        // Tropical/typhoon WATCH (non-warning; the warning is primary above):
        // high winds possible → wind predictor, so a hurricane watch over the
        // corridor contributes instead of scoring zero.
        if e.contains("hurricane") || e.contains("typhoon") || e.contains("tropical storm") { return "wind" }
        if e.contains("wind") { return "wind" }
        if e.contains("air quality") || e.contains("smoke") || e.contains("dust")
            || e.contains("fog") { return "air" }
        if e.contains("flood") { return "precip" }        // Flood Watch/Advisory
        if e.contains("tornado") || e.contains("thunderstorm") || e.contains("storm") {
            return "convective"                            // watch / general storm → predictor
        }
        // Tsunami Watch/Advisory (strong-current coastal hazard, marginal road
        // relevance; the tsunami WARNING is scored primary above) is left
        // unscored rather than forced into an ill-fitting predictor family.
        return nil
    }
}


/// How a whole route's risk band is decided from its pieces.
enum RouteRiskBand {
    /// The band to LABEL a route with.
    ///
    /// Normally this is the distance-weighted average: what fraction of the
    /// miles you actually travel sit at what risk. A minority yellow stretch
    /// should not paint an otherwise clear trip yellow.
    ///
    /// A RED peak is different, and is a floor rather than an average. You
    /// cannot average your way out of a tornado warning: two miles of it in
    /// the middle of a twenty-mile trip is not a green trip, and diluting it
    /// is how the same corridor came out full red for driving and half green
    /// for walking — the two modes sample the same ground at different
    /// densities, so any average disagrees with itself between them. A
    /// life-safety hazard on the path is the same hazard whichever way you
    /// are travelling.
    static func displayed(weighted: Double, peak: Double) -> Double {
        FlowsCore.riskBand(score: peak) == .red ? max(weighted, peak) : weighted
    }
}
