// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsAlertVehicle { bool has; uint8_t kind; bool has_color; int64_t color_index; bool has_brand; int64_t brand_index; } __swift_bridge__$FlowsAlertVehicle;
typedef struct __swift_bridge__$Option$FlowsAlertVehicle { bool is_some; __swift_bridge__$FlowsAlertVehicle val; } __swift_bridge__$Option$FlowsAlertVehicle;
typedef struct __swift_bridge__$FlowsAlertPerson { bool has; bool is_child; bool has_color; int64_t color_index; } __swift_bridge__$FlowsAlertPerson;
typedef struct __swift_bridge__$Option$FlowsAlertPerson { bool is_some; __swift_bridge__$FlowsAlertPerson val; } __swift_bridge__$Option$FlowsAlertPerson;
typedef struct __swift_bridge__$FlowsAlertEscalation { double baseline; bool has_trigger; uint8_t trigger_kind; double risk; } __swift_bridge__$FlowsAlertEscalation;
typedef struct __swift_bridge__$Option$FlowsAlertEscalation { bool is_some; __swift_bridge__$FlowsAlertEscalation val; } __swift_bridge__$Option$FlowsAlertEscalation;
struct __swift_bridge__$FlowsAlertEscalation __swift_bridge__$flows_alert_text_evaluate_escalation(bool complete, double mean, double peak, struct RustStr peak_alert_id, bool has_peak_alert_id, double baseline, double dismissed_risk, struct RustStr dismissed_joined, struct __private__FfiSlice dismissed_lens, int64_t dismissed_count);
void* __swift_bridge__$flows_alert_text_escalation_constants(void);
void* __swift_bridge__$flows_alert_text_color_names(void);
void* __swift_bridge__$flows_alert_text_brands(void);
bool __swift_bridge__$flows_alert_text_describes_an_entity(struct RustStr event);
struct __swift_bridge__$FlowsAlertVehicle __swift_bridge__$flows_alert_text_vehicle(struct RustStr text);
struct __swift_bridge__$FlowsAlertPerson __swift_bridge__$flows_alert_text_person(struct RustStr text);
void* __swift_bridge__$flows_alert_text_phrases(uint8_t kind);
void* __swift_bridge__$flows_alert_text_match_order(void);
void* __swift_bridge__$flows_alert_text_road_words(void);
int64_t __swift_bridge__$flows_alert_text_call_kind(struct RustStr transcript);
void* __swift_bridge__$flows_alert_text_place_phrase(struct RustStr transcript);
double __swift_bridge__$flows_alert_text_lifetime_seconds(uint8_t kind);
bool __swift_bridge__$flows_alert_text_is_expired(uint8_t kind, double heard_at, double now);
void* __swift_bridge__$flows_alert_text_pin_constants(void);
void* __swift_bridge__$flows_alert_text_visible(struct __private__FfiSlice kinds, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice heard_at, bool has_position, double lat, double lon, struct __private__FfiSlice corridor_lats, struct __private__FfiSlice corridor_lons, int64_t corridor_count, double now);
void* __swift_bridge__$flows_alert_text_merged_keep(struct __private__FfiSlice kinds, struct __private__FfiSlice lats, struct __private__FfiSlice lons, uint8_t new_kind, double new_lat, double new_lon);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
void* __swift_bridge__$flows_alerts_display_kind_names(void);
int32_t __swift_bridge__$flows_alerts_display_kind(struct RustStr event);
int32_t __swift_bridge__$flows_alerts_display_kind_for_family(struct RustStr family);
int32_t __swift_bridge__$flows_alerts_shelter_kind(struct RustStr event, double severity_score);
bool __swift_bridge__$flows_alerts_is_life_safety(struct RustStr event);
bool __swift_bridge__$flows_alerts_is_lookout(struct RustStr event);
int32_t __swift_bridge__$flows_alerts_action(struct RustStr event, double severity_score, bool has_expiry, double seconds_until_expiry);
int32_t __swift_bridge__$flows_alerts_threat_rank(struct RustStr event, double severity_score);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsClimateProfile { double has; int64_t band; double comfort_low_f; double comfort_high_f; double record_low_f; double record_high_f; double wind_low; double wind_medium; double wind_high; double pop_low; double pop_medium; double pop_high; } __swift_bridge__$FlowsClimateProfile;
typedef struct __swift_bridge__$Option$FlowsClimateProfile { bool is_some; __swift_bridge__$FlowsClimateProfile val; } __swift_bridge__$Option$FlowsClimateProfile;
typedef struct __swift_bridge__$FlowsClimateNorms { double week_low_f; double week_high_f; double wind_mean_mph; double wind_sigma_mph; } __swift_bridge__$FlowsClimateNorms;
typedef struct __swift_bridge__$Option$FlowsClimateNorms { bool is_some; __swift_bridge__$FlowsClimateNorms val; } __swift_bridge__$Option$FlowsClimateNorms;
typedef struct __swift_bridge__$FlowsClimateSolarTerms { double declination; double equation_of_time; } __swift_bridge__$FlowsClimateSolarTerms;
typedef struct __swift_bridge__$Option$FlowsClimateSolarTerms { bool is_some; __swift_bridge__$FlowsClimateSolarTerms val; } __swift_bridge__$Option$FlowsClimateSolarTerms;
typedef struct __swift_bridge__$FlowsClimateTwilight { double has; double dawn; double dusk; } __swift_bridge__$FlowsClimateTwilight;
typedef struct __swift_bridge__$Option$FlowsClimateTwilight { bool is_some; __swift_bridge__$FlowsClimateTwilight val; } __swift_bridge__$Option$FlowsClimateTwilight;
typedef struct __swift_bridge__$FlowsClimateWeekTrig { double cos_t; double sin_t; double cos_2t; double sin_2t; } __swift_bridge__$FlowsClimateWeekTrig;
typedef struct __swift_bridge__$Option$FlowsClimateWeekTrig { bool is_some; __swift_bridge__$FlowsClimateWeekTrig val; } __swift_bridge__$Option$FlowsClimateWeekTrig;
typedef struct __swift_bridge__$FlowsClimateOptional { double is_some; double value; } __swift_bridge__$FlowsClimateOptional;
typedef struct __swift_bridge__$Option$FlowsClimateOptional { bool is_some; __swift_bridge__$FlowsClimateOptional val; } __swift_bridge__$Option$FlowsClimateOptional;
typedef struct __swift_bridge__$FlowsClimateCell { bool has; int64_t key; } __swift_bridge__$FlowsClimateCell;
typedef struct __swift_bridge__$Option$FlowsClimateCell { bool is_some; __swift_bridge__$FlowsClimateCell val; } __swift_bridge__$Option$FlowsClimateCell;
typedef struct FlowsHarmonicTable FlowsHarmonicTable;
void __swift_bridge__$FlowsHarmonicTable$_free(void* self);

void* __swift_bridge__$Vec_FlowsHarmonicTable$new(void);
void __swift_bridge__$Vec_FlowsHarmonicTable$drop(void* vec_ptr);
void __swift_bridge__$Vec_FlowsHarmonicTable$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FlowsHarmonicTable$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsHarmonicTable$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FlowsHarmonicTable$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FlowsHarmonicTable$len(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsHarmonicTable$as_ptr(void* vec_ptr);

double __swift_bridge__$flows_climate_south_anchor(void);
double __swift_bridge__$flows_climate_north_anchor(void);
double __swift_bridge__$flows_climate_pitch_degrees(void);
double __swift_bridge__$flows_climate_min_latitude(void);
double __swift_bridge__$flows_climate_max_latitude(void);
double __swift_bridge__$flows_climate_reference_elevation_meters(void);
double __swift_bridge__$flows_climate_meters_per_band_step(void);
struct __swift_bridge__$FlowsClimateOptional __swift_bridge__$flows_climate_band_index(double latitude);
int64_t __swift_bridge__$flows_climate_elevation_band_shift(double elevation_meters, bool has_elevation);
struct __swift_bridge__$FlowsClimateProfile __swift_bridge__$flows_climate_band_profile(double latitude, double elevation_meters, bool has_elevation);
void* __swift_bridge__$flows_climate_type_names(void);
struct __swift_bridge__$FlowsClimateProfile __swift_bridge__$flows_climate_type_profile(uint8_t code);
uint8_t __swift_bridge__$flows_climate_classify(double latitude, double longitude, double elevation_meters, bool has_elevation);
double __swift_bridge__$flows_climate_temp_sigma_f(void);
struct __swift_bridge__$FlowsClimateNorms __swift_bridge__$flows_climate_seasonal_norms(int64_t week, double latitude, double longitude, double elevation_meters, bool has_elevation);
bool __swift_bridge__$flows_climate_temperature_beyond_normal(double temp_f, double week_low_f, double week_high_f, double wind_mean_mph, double wind_sigma_mph);
bool __swift_bridge__$flows_climate_wind_beyond_normal(double wind_mph, double week_low_f, double week_high_f, double wind_mean_mph, double wind_sigma_mph);
struct __swift_bridge__$FlowsClimateProfile __swift_bridge__$flows_climate_profile(double latitude, double longitude, double elevation_meters, bool has_elevation);
struct __swift_bridge__$FlowsClimateCell __swift_bridge__$flows_climate_precise_cell(double latitude, double longitude);
bool __swift_bridge__$flows_climate_precise_cell_near_home(int64_t key, double home_latitude, double home_longitude);
double __swift_bridge__$flows_climate_civil_twilight_degrees(void);
double __swift_bridge__$flows_climate_julian_day(double now);
double __swift_bridge__$flows_climate_midnight_jd(double jd);
struct __swift_bridge__$FlowsClimateSolarTerms __swift_bridge__$flows_climate_solar_terms(double jd);
double __swift_bridge__$flows_climate_hour_angle_minutes(double latitude, double declination, double angle);
struct __swift_bridge__$FlowsClimateTwilight __swift_bridge__$flows_climate_twilight(double latitude, double longitude, double now, double angle);
bool __swift_bridge__$flows_climate_is_night(double latitude, double longitude, double now);
double __swift_bridge__$flows_climate_solar_elevation(double latitude, double longitude, double now);
double __swift_bridge__$flows_climate_next_change(double latitude, double longitude, double now);
double __swift_bridge__$flows_climate_score_max(void);
struct __swift_bridge__$FlowsClimateWeekTrig __swift_bridge__$flows_climate_week_trig(int64_t week);
bool __swift_bridge__$flows_climate_is_active(double expires, bool has_expires, double arrival_offset, double now);
int64_t __swift_bridge__$flows_climate_max_arrival_samples(void);
void* __swift_bridge__$flows_climate_arrival_offsets(int64_t sample_count, double total_travel_seconds);
void* __swift_bridge__$flows_climate_parse_flhh(struct __private__FfiSlice data);
void* __swift_bridge__$FlowsHarmonicTable$families(void* self);
void* __swift_bridge__$FlowsHarmonicTable$zips(void* self);
uint32_t __swift_bridge__$FlowsHarmonicTable$family_count(void* self);
int32_t __swift_bridge__$FlowsHarmonicTable$zip_index(void* self, struct RustStr zip);
struct __swift_bridge__$FlowsClimateOptional __swift_bridge__$FlowsHarmonicTable$score_named(void* self, struct RustStr zip, struct RustStr family, int64_t week);
double __swift_bridge__$FlowsHarmonicTable$score_row(void* self, int64_t zip_index, int64_t family_index, double cos_t, double sin_t, double cos_2t, double sin_2t);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
void* __swift_bridge__$flows_forecast_predictor_family_names(void);
double __swift_bridge__$flows_forecast_score(double temperature_f, bool has_temperature, double wind_mph, bool has_wind, double pop_percent, bool has_pop, double latitude, double longitude, double elevation_meters, bool has_elevation);
void* __swift_bridge__$flows_forecast_predictor_families(double temperature_f, bool has_temperature, double wind_mph, bool has_wind, double pop_percent, bool has_pop, double latitude, double longitude, double elevation_meters, bool has_elevation);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
double __swift_bridge__$flows_geo_bearing_degrees(double a_lat, double a_lon, double b_lat, double b_lon);
double __swift_bridge__$flows_geo_ahead_cone_degrees(void);
double __swift_bridge__$flows_geo_fuel_corridor_meters(void);
bool __swift_bridge__$flows_geo_fuel_station_is_reachable(double station_lat, double station_lon, double here_lat, double here_lon, double course_degrees, struct __private__FfiSlice route_lats, struct __private__FfiSlice route_lons, int64_t route_count, double corridor_meters);
int64_t __swift_bridge__$flows_geo_corridor_nearest(struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice point_counts, int64_t corridor_count, double lat, double lon);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct FlowsHazardSnapshot FlowsHazardSnapshot;
void __swift_bridge__$FlowsHazardSnapshot$_free(void* self);

void* __swift_bridge__$Vec_FlowsHazardSnapshot$new(void);
void __swift_bridge__$Vec_FlowsHazardSnapshot$drop(void* vec_ptr);
void __swift_bridge__$Vec_FlowsHazardSnapshot$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FlowsHazardSnapshot$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsHazardSnapshot$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FlowsHazardSnapshot$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FlowsHazardSnapshot$len(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsHazardSnapshot$as_ptr(void* vec_ptr);

double __swift_bridge__$flows_hazard_air_score(double us_aqi);
double __swift_bridge__$flows_hazard_uv_score(double index);
double __swift_bridge__$flows_hazard_space_weather_score(int64_t scale);
double __swift_bridge__$flows_hazard_radiation_space_weather_score(int64_t s_scale, int64_t g_scale, double latitude);
double __swift_bridge__$flows_hazard_volcano_alert_score(struct RustStr level);
double __swift_bridge__$flows_hazard_avalanche_rating_score(int64_t rating);
double __swift_bridge__$flows_hazard_tropical_intensity_score(double max_wind_kt);
double __swift_bridge__$flows_hazard_tsunami_level_score(struct RustStr level);
double __swift_bridge__$flows_hazard_spc_categorical_score(int64_t dn);
double __swift_bridge__$flows_hazard_flood_category_score(struct RustStr category);
double __swift_bridge__$flows_hazard_severity_score(struct RustStr severity);
double __swift_bridge__$flows_hazard_backup_severity(struct RustStr phenomena);
double __swift_bridge__$flows_hazard_fire_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice frps, double lat, double lon);
double __swift_bridge__$flows_hazard_seismic_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice magnitudes, struct __private__FfiSlice age_hours, double lat, double lon);
double __swift_bridge__$flows_hazard_water_proximity_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
double __swift_bridge__$flows_hazard_closure_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
double __swift_bridge__$flows_hazard_tropical_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice max_wind_kts, double lat, double lon);
double __swift_bridge__$flows_hazard_flood_gauge_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct RustStr categories_joined, double lat, double lon);
double __swift_bridge__$flows_hazard_volcanic_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct RustStr levels_joined, double lat, double lon);
double __swift_bridge__$flows_hazard_tsunami_score(struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct RustStr levels_joined, double lat, double lon);
bool __swift_bridge__$flows_hazard_point_in_polygon(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
bool __swift_bridge__$flows_hazard_ring_contains(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
double __swift_bridge__$flows_hazard_fire_perimeter_score(struct __private__FfiSlice ring_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
double __swift_bridge__$flows_hazard_avalanche_score(struct __private__FfiSlice zone_ring_counts, struct __private__FfiSlice ratings, struct __private__FfiSlice ring_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
double __swift_bridge__$flows_hazard_outlook_score(struct __private__FfiSlice zone_ring_counts, struct __private__FfiSlice scores, struct __private__FfiSlice ring_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
void* __swift_bridge__$flows_hazard_cell_key(double lat, double lon);
void* __swift_bridge__$flows_hazard_states_containing(double lat, double lon);
void* __swift_bridge__$flows_hazard_marine_regions_containing(double lat, double lon);
void* __swift_bridge__$flows_hazard_provisional_samples(struct __private__FfiSlice sample_lats, struct __private__FfiSlice sample_lons, struct __private__FfiSlice alert_severities, struct __private__FfiSlice alert_expires, struct __private__FfiSlice alert_has_expires, struct RustStr cell_keys_joined, struct __private__FfiSlice cell_alert_counts, struct __private__FfiSlice cell_alert_indices, struct __private__FfiSlice arrival_offsets, bool has_offsets, double now);
void* __swift_bridge__$flows_hazard_alerts_covering(double lat, double lon, struct __private__FfiSlice alert_ring_counts, struct __private__FfiSlice alert_zone_counts, struct __private__FfiSlice ring_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct RustStr alert_zones_joined, struct RustStr zone_names_joined, struct __private__FfiSlice zone_ring_counts, struct __private__FfiSlice zone_ring_lens, struct __private__FfiSlice zone_lats, struct __private__FfiSlice zone_lons);
void* __swift_bridge__$flows_hazard_all_rings(struct __private__FfiSlice ring_coord_counts, struct __private__FfiSlice coord_lens, struct __private__FfiSlice values, int64_t max_points);
double __swift_bridge__$flows_hazard_corridor_noisy_or(struct __private__FfiSlice severities, struct __private__FfiSlice coverages);
double __swift_bridge__$flows_hazard_corridor_coverage(struct __private__FfiSlice risks);
void* __swift_bridge__$flows_hazard_worst_first(struct __private__FfiSlice severities);
void* __swift_bridge__$flows_hazard_fuel_prices(struct RustStr xml);
void* __swift_bridge__$flows_hazard_fuel_places(struct RustStr xml);
double __swift_bridge__$flows_hazard_clip_margin_degrees(void);
void* __swift_bridge__$flows_hazard_snapshot_new(void);
void __swift_bridge__$FlowsHazardSnapshot$add_hotspots(void* self, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice frps);
void __swift_bridge__$FlowsHazardSnapshot$add_perimeters(void* self, struct __private__FfiSlice ring_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons);
void __swift_bridge__$FlowsHazardSnapshot$add_quakes(void* self, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice magnitudes, struct __private__FfiSlice age_hours);
void __swift_bridge__$FlowsHazardSnapshot$set_space(void* self, int64_t r, int64_t s, int64_t g);
void __swift_bridge__$FlowsHazardSnapshot$add_volcanoes(void* self, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct RustStr levels_joined);
void __swift_bridge__$FlowsHazardSnapshot$add_avalanche_zones(void* self, struct __private__FfiSlice zone_ring_counts, struct __private__FfiSlice ratings, struct __private__FfiSlice ring_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons);
void __swift_bridge__$FlowsHazardSnapshot$add_storms(void* self, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice max_wind_kts);
void __swift_bridge__$FlowsHazardSnapshot$add_tsunamis(void* self, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct RustStr levels_joined);
void __swift_bridge__$FlowsHazardSnapshot$add_spc_zones(void* self, struct __private__FfiSlice zone_ring_counts, struct __private__FfiSlice scores, struct __private__FfiSlice ring_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons);
void* __swift_bridge__$FlowsHazardSnapshot$clipped(void* self, double min_lat, double min_lon, double max_lat, double max_lon);
void* __swift_bridge__$FlowsHazardSnapshot$live(void* self, double lat, double lon);
void* __swift_bridge__$FlowsHazardSnapshot$hotspots_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$perimeters_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$quakes_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$space(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$volcanoes_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$volcano_levels(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$avalanche_zones_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$avalanche_ratings(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$storms_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$tsunamis_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$tsunami_levels(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$spc_zones_flat(void* self);
void* __swift_bridge__$FlowsHazardSnapshot$spc_scores(void* self);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsLearningOptional { double is_some; double value; } __swift_bridge__$FlowsLearningOptional;
typedef struct __swift_bridge__$Option$FlowsLearningOptional { bool is_some; __swift_bridge__$FlowsLearningOptional val; } __swift_bridge__$Option$FlowsLearningOptional;
typedef struct __swift_bridge__$FlowsLearningCell { double weighted_sum; double weight; double count; } __swift_bridge__$FlowsLearningCell;
typedef struct __swift_bridge__$Option$FlowsLearningCell { bool is_some; __swift_bridge__$FlowsLearningCell val; } __swift_bridge__$Option$FlowsLearningCell;
typedef struct __swift_bridge__$FlowsLearningCellUpdate { double has; double weighted_sum; double weight; double count; } __swift_bridge__$FlowsLearningCellUpdate;
typedef struct __swift_bridge__$Option$FlowsLearningCellUpdate { bool is_some; __swift_bridge__$FlowsLearningCellUpdate val; } __swift_bridge__$Option$FlowsLearningCellUpdate;
typedef struct __swift_bridge__$FlowsLearningDecay { double apply; double factor; double last_decay; } __swift_bridge__$FlowsLearningDecay;
typedef struct __swift_bridge__$Option$FlowsLearningDecay { bool is_some; __swift_bridge__$FlowsLearningDecay val; } __swift_bridge__$Option$FlowsLearningDecay;
typedef struct __swift_bridge__$FlowsLearningEta { double has; double log_ratio; int64_t samples; } __swift_bridge__$FlowsLearningEta;
typedef struct __swift_bridge__$Option$FlowsLearningEta { bool is_some; __swift_bridge__$FlowsLearningEta val; } __swift_bridge__$Option$FlowsLearningEta;
double __swift_bridge__$flows_learning_everyday_default_miles(void);
double __swift_bridge__$flows_learning_everyday_floor_miles(void);
double __swift_bridge__$flows_learning_everyday_hard_cap_miles(void);
int64_t __swift_bridge__$flows_learning_everyday_min_trips_for_radius(void);
int64_t __swift_bridge__$flows_learning_everyday_trip_window(void);
int64_t __swift_bridge__$flows_learning_everyday_max_places_per_category(void);
int64_t __swift_bridge__$flows_learning_everyday_feature_index_space(void);
int64_t __swift_bridge__$flows_learning_everyday_feature_count(void);
struct __swift_bridge__$FlowsLearningOptional __swift_bridge__$flows_learning_everyday_quantile(struct __private__FfiSlice values, double q);
double __swift_bridge__$flows_learning_everyday_radius_miles(struct __private__FfiSlice trip_miles);
struct __swift_bridge__$FlowsLearningOptional __swift_bridge__$flows_learning_everyday_mean_trip_miles(struct __private__FfiSlice trip_miles);
struct __swift_bridge__$FlowsLearningOptional __swift_bridge__$flows_learning_everyday_trip_miles_sd(struct __private__FfiSlice trip_miles);
double __swift_bridge__$flows_learning_everyday_miles(double a_lat, double a_lon, double b_lat, double b_lon);
bool __swift_bridge__$flows_learning_everyday_accepts_trip(double miles);
int64_t __swift_bridge__$flows_learning_everyday_hour_bucket(int64_t hour);
int32_t __swift_bridge__$flows_learning_everyday_feature_index(struct RustStr raw);
void* __swift_bridge__$flows_learning_everyday_features(int64_t hour_bucket, bool weekend, double start_lat, double start_lon, double place_lat, double place_lon, int64_t feature_index);
void* __swift_bridge__$flows_learning_everyday_ranked_order(struct __private__FfiSlice uses, struct __private__FfiSlice seen, struct __private__FfiSlice last_used, struct RustStr names_joined);
int32_t __swift_bridge__$flows_learning_everyday_evict_index(struct __private__FfiSlice uses, struct __private__FfiSlice seen, struct __private__FfiSlice last_used);
struct __swift_bridge__$FlowsLearningDecay __swift_bridge__$flows_learning_decay_plan(double last_decay, double now, double half_life_seconds);
double __swift_bridge__$flows_learning_traffic_half_life_seconds(void);
int64_t __swift_bridge__$flows_learning_traffic_confident_after(void);
double __swift_bridge__$flows_learning_traffic_max_factor(void);
double __swift_bridge__$flows_learning_traffic_min_factor(void);
void* __swift_bridge__$flows_learning_traffic_weather_names(void);
uint8_t __swift_bridge__$flows_learning_traffic_weather_from_family(struct RustStr family, bool has_family);
bool __swift_bridge__$flows_learning_road_class_is_highway(double average_mph);
double __swift_bridge__$flows_learning_delay_cell_mean(double weighted_sum, double weight);
bool __swift_bridge__$flows_learning_traffic_accepts(double predicted_seconds, double actual_seconds);
struct __swift_bridge__$FlowsLearningCellUpdate __swift_bridge__$flows_learning_traffic_add(double weighted_sum, double weight, int64_t count, double predicted_seconds, double actual_seconds);
double __swift_bridge__$flows_learning_traffic_factor(bool is_highway, struct __swift_bridge__$FlowsLearningCell local, bool has_local, struct __swift_bridge__$FlowsLearningCell pooled, bool has_pooled);
double __swift_bridge__$flows_learning_traffic_adjusted_seconds(double router_seconds, bool is_highway, struct __swift_bridge__$FlowsLearningCell local, bool has_local, struct __swift_bridge__$FlowsLearningCell pooled, bool has_pooled);
struct __swift_bridge__$FlowsLearningOptional __swift_bridge__$flows_learning_traffic_delay_minutes(double router_seconds, bool is_highway, struct __swift_bridge__$FlowsLearningCell local, bool has_local, struct __swift_bridge__$FlowsLearningCell pooled, bool has_pooled);
bool __swift_bridge__$flows_learning_traffic_is_confident(int64_t count);
double __swift_bridge__$flows_learning_efficiency_half_life_seconds(void);
double __swift_bridge__$flows_learning_efficiency_confident_miles(void);
double __swift_bridge__$flows_learning_efficiency_min_ratio(void);
double __swift_bridge__$flows_learning_efficiency_max_ratio(void);
double __swift_bridge__$flows_learning_efficiency_cell_mean(double weighted_sum, double weight);
bool __swift_bridge__$flows_learning_efficiency_accepts(double miles_driven, double units_burned);
struct __swift_bridge__$FlowsLearningCell __swift_bridge__$flows_learning_efficiency_add(double weighted_sum, double weight, double miles, double miles_driven, double units_burned);
double __swift_bridge__$flows_learning_efficiency_economy(double rated_miles_per_unit, bool is_highway, struct __swift_bridge__$FlowsLearningCell local, bool has_local, struct __swift_bridge__$FlowsLearningCell pooled, bool has_pooled);
bool __swift_bridge__$flows_learning_efficiency_is_confident(double miles);
double __swift_bridge__$flows_learning_buffer_alpha(void);
int64_t __swift_bridge__$flows_learning_buffer_min_samples_to_trust(void);
double __swift_bridge__$flows_learning_buffer_plausible_low(void);
double __swift_bridge__$flows_learning_buffer_plausible_high(void);
bool __swift_bridge__$flows_learning_buffer_is_usable(double sample);
struct __swift_bridge__$FlowsLearningOptional __swift_bridge__$flows_learning_buffer_updated(double mean, bool has_mean, double sample);
double __swift_bridge__$flows_learning_buffer_wait_seconds(double prior, double learned_mean, bool has_mean, int64_t samples);
double __swift_bridge__$flows_learning_refuel_accuracy_floor(void);
int64_t __swift_bridge__$flows_learning_refuel_window(void);
int64_t __swift_bridge__$flows_learning_refuel_retained(void);
double __swift_bridge__$flows_learning_stale_gauge_gap_seconds(void);
double __swift_bridge__$flows_learning_refuel_accuracy(struct __private__FfiSlice errors);
double __swift_bridge__$flows_learning_refuel_error(double predicted_fraction, double reported_fraction);
bool __swift_bridge__$flows_learning_refuel_should_prompt(bool check_ins_enabled, double accuracy);
bool __swift_bridge__$flows_learning_gauge_went_stale(double last_used, bool has_last_used, double now);
double __swift_bridge__$flows_learning_eta_min_plausible_ratio(void);
double __swift_bridge__$flows_learning_eta_max_plausible_ratio(void);
int64_t __swift_bridge__$flows_learning_eta_min_samples_to_apply(void);
double __swift_bridge__$flows_learning_eta_min_meaningful_deviation(void);
double __swift_bridge__$flows_learning_eta_clamp_low(void);
double __swift_bridge__$flows_learning_eta_clamp_high(void);
double __swift_bridge__$flows_learning_eta_multiplier(double log_ratio, int64_t samples);
struct __swift_bridge__$FlowsLearningEta __swift_bridge__$flows_learning_eta_record(double log_ratio, int64_t samples, double predicted_seconds, double actual_seconds, double stopped_seconds);
double __swift_bridge__$flows_learning_destination_recency_half_life_days(void);
double __swift_bridge__$flows_learning_destination_context_weight(void);
double __swift_bridge__$flows_learning_destination_time_weight(void);
double __swift_bridge__$flows_learning_destination_base_weight(void);
uint8_t __swift_bridge__$flows_learning_destination_reason(int64_t context_hits, int64_t time_hits, int64_t total_hits);
void* __swift_bridge__$flows_learning_destination_rank(struct __private__FfiSlice context_hits, struct __private__FfiSlice time_hits, struct __private__FfiSlice total_hits, struct __private__FfiSlice last_used, double now, int64_t limit);
bool __swift_bridge__$flows_learning_destination_is_confident(double top_score, bool has_top, int64_t minimum_evidence);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsLongTripsDay { double day; double meters; } __swift_bridge__$FlowsLongTripsDay;
typedef struct __swift_bridge__$Option$FlowsLongTripsDay { bool is_some; __swift_bridge__$FlowsLongTripsDay val; } __swift_bridge__$Option$FlowsLongTripsDay;
double __swift_bridge__$flows_long_trips_fuel_severity(double fraction);
uint8_t __swift_bridge__$flows_long_trips_fuel_band(double fraction);
int64_t __swift_bridge__$flows_long_trips_warn_at_reachable_count(void);
void* __swift_bridge__$flows_long_trips_reachable_stations(struct __private__FfiSlice miles, struct __private__FfiSlice prices, struct __private__FfiSlice priced, int64_t count, double range_miles, double reserve_miles);
int64_t __swift_bridge__$flows_long_trips_fuel_level(struct __private__FfiSlice miles, struct __private__FfiSlice prices, struct __private__FfiSlice priced, int64_t count, double range_miles, double reserve_miles);
int64_t __swift_bridge__$flows_long_trips_cheapest_station(struct __private__FfiSlice miles, struct __private__FfiSlice prices, struct __private__FfiSlice priced, int64_t count, double range_miles, double reserve_miles);
bool __swift_bridge__$flows_long_trips_should_offer_share(double route_meters, double driven_today_meters);
void* __swift_bridge__$flows_long_trips_share_constants(void);
void* __swift_bridge__$flows_long_trips_share_caps(void);
struct __swift_bridge__$FlowsLongTripsDay __swift_bridge__$flows_long_trips_daily_drive_add(double day, double meters, double today, double delta);
void* __swift_bridge__$flows_long_trips_ranked_recipients(struct __private__FfiSlice dates, struct __private__FfiSlice date_counts, int64_t recipient_count, double now);
void* __swift_bridge__$flows_long_trips_normalized_phone(struct RustStr phone);
void* __swift_bridge__$flows_long_trips_record_share(struct RustStr phones, struct __private__FfiSlice phone_lengths, struct __private__FfiSlice dates, struct __private__FfiSlice date_counts, int64_t recipient_count, struct RustStr name, struct RustStr phone, double date);
void* __swift_bridge__$flows_long_trips_corridor_constants(void);
void* __swift_bridge__$flows_long_trips_corridor_limits(void);
bool __swift_bridge__$flows_long_trips_keep_corridor(double saved_at, struct __private__FfiSlice lats, struct __private__FfiSlice lons, int64_t count, double now, double lat, double lon, bool has_position);
void* __swift_bridge__$flows_long_trips_prune_corridors(struct __private__FfiSlice saved_at, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice point_counts, int64_t corridor_count, double now, double lat, double lon, bool has_position);
bool __swift_bridge__$flows_long_trips_worth_saving(double trip_meters);
bool __swift_bridge__$flows_long_trips_supersedes(double newer_lat, double newer_lon, bool has_newer, double older_lat, double older_lon, bool has_older);
void* __swift_bridge__$flows_long_trips_decimate(struct __private__FfiSlice lats, struct __private__FfiSlice lons, int64_t count, double step_meters, int64_t limit);
void* __swift_bridge__$flows_long_trips_record_corridor(struct __private__FfiSlice saved_at, struct __private__FfiSlice end_lats, struct __private__FfiSlice end_lons, struct __private__FfiSlice has_end, int64_t corridor_count, double new_lat, double new_lon, bool has_new, double now);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsModesTuning { int64_t max_in_flight; int64_t planning_max_in_flight; int64_t viewport_grid_span; double ttl_multiplier; double debounce_seconds; } __swift_bridge__$FlowsModesTuning;
typedef struct __swift_bridge__$Option$FlowsModesTuning { bool is_some; __swift_bridge__$FlowsModesTuning val; } __swift_bridge__$Option$FlowsModesTuning;
typedef struct __swift_bridge__$FlowsModesNearest { bool has; int64_t index; double meters; } __swift_bridge__$FlowsModesNearest;
typedef struct __swift_bridge__$Option$FlowsModesNearest { bool is_some; __swift_bridge__$FlowsModesNearest val; } __swift_bridge__$Option$FlowsModesNearest;
typedef struct __swift_bridge__$FlowsModesMinutes { bool has; int64_t minutes; double interval_seconds; } __swift_bridge__$FlowsModesMinutes;
typedef struct __swift_bridge__$Option$FlowsModesMinutes { bool is_some; __swift_bridge__$FlowsModesMinutes val; } __swift_bridge__$Option$FlowsModesMinutes;
typedef struct __swift_bridge__$FlowsModesRideOffer { bool has; double ride_miles; double ride_seconds; double walk_seconds; double cost_usd; } __swift_bridge__$FlowsModesRideOffer;
typedef struct __swift_bridge__$Option$FlowsModesRideOffer { bool is_some; __swift_bridge__$FlowsModesRideOffer val; } __swift_bridge__$Option$FlowsModesRideOffer;
uint8_t __swift_bridge__$flows_modes_signal_tier(struct RustStr radio_technology, bool has_technology, bool on_wifi, bool offline);
bool __swift_bridge__$flows_modes_should_pre_stage(uint8_t tier, bool buffer_draining, int64_t recent_stalls);
bool __swift_bridge__$flows_modes_is_draining(double previous, bool has_previous, double current, bool has_current);
uint8_t __swift_bridge__$flows_modes_device_tier(int64_t cores, double memory_gb);
struct __swift_bridge__$FlowsModesTuning __swift_bridge__$flows_modes_tuning_settings(uint8_t tier, int64_t thermal, bool low_power);
uint8_t __swift_bridge__$flows_modes_on_connection_lost(bool is_playing, bool needs_network, bool has_local_music, struct RustStr last_genre, bool has_genre);
void* __swift_bridge__$flows_modes_fallback_genre(struct RustStr last_genre, bool has_genre);
bool __swift_bridge__$flows_modes_should_restore(bool handed_off, bool connection_held, bool driver_chose_since);
double __swift_bridge__$flows_modes_restore_hold_seconds(void);
double __swift_bridge__$flows_modes_grace_seconds(uint8_t source, double measured_buffer, bool has_buffer);
void* __swift_bridge__$flows_modes_grace_caps(void);
struct __swift_bridge__$FlowsModesNearest __swift_bridge__$flows_modes_nearest_station(double lat, double lon, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice exact);
int64_t __swift_bridge__$flows_modes_retarget(struct RustStr playing_id, double playing_lat, double playing_lon, bool has_playing_coordinate, double lat, double lon, struct RustStr ids_joined, struct __private__FfiSlice id_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice exact);
double __swift_bridge__$flows_modes_switch_margin(void);
int64_t __swift_bridge__$flows_modes_nearest_within(double lat, double lon, double max_meters, struct __private__FfiSlice lats, struct __private__FfiSlice lons);
bool __swift_bridge__$flows_modes_should_record(double lat, double lon, double last_lat, double last_lon, bool has_last);
double __swift_bridge__$flows_modes_way_back_meters(struct __private__FfiSlice lats, struct __private__FfiSlice lons);
double __swift_bridge__$flows_modes_min_step_meters(void);
int64_t __swift_bridge__$flows_modes_max_points(void);
bool __swift_bridge__$flows_modes_worth_flying(double trip_miles);
double __swift_bridge__$flows_modes_flight_seconds(double airport_miles);
double __swift_bridge__$flows_modes_door_seconds(double airport_miles);
double __swift_bridge__$flows_modes_fare_estimate(double airport_miles);
int64_t __swift_bridge__$flows_modes_airport_score(struct RustStr name);
int64_t __swift_bridge__$flows_modes_pick_airport(struct RustStr names_joined, struct __private__FfiSlice name_lens, struct __private__FfiSlice meters, double max_meters);
void* __swift_bridge__$flows_modes_air_constants(void);
bool __swift_bridge__$flows_modes_is_peak(int64_t local_minutes);
struct __swift_bridge__$FlowsModesMinutes __swift_bridge__$flows_modes_local_minutes(double reference_seconds, double longitude);
void* __swift_bridge__$flows_modes_traffic_constants(void);
bool __swift_bridge__$flows_modes_keeps_road_choice(uint8_t leg_kind, bool leg_has_tolls, uint8_t candidate_kind, bool candidate_has_tolls, bool candidate_has_highways, bool no_tolls, bool no_highways);
bool __swift_bridge__$flows_modes_faster_saves_enough(double current_seconds, double candidate_seconds, double tolerance_seconds);
void* __swift_bridge__$flows_modes_off_line_spans(struct __private__FfiSlice candidate_lats, struct __private__FfiSlice candidate_lons, struct __private__FfiSlice road_lats, struct __private__FfiSlice road_lons);
double __swift_bridge__$flows_modes_detour_check_spacing(struct __private__FfiSlice spans, double candidate_meters);
bool __swift_bridge__$flows_modes_spans_checked(struct __private__FfiSlice spans, struct __private__FfiSlice check_alongs);
void* __swift_bridge__$flows_modes_nearest_on_line(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
uint8_t __swift_bridge__$flows_modes_faster_risk_verdict(bool candidate_complete, double candidate_risk, bool ahead_known, double ahead_risk, bool limits_unchecked);
void* __swift_bridge__$flows_modes_risk_clusters(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double adjacency_meters);
void* __swift_bridge__$flows_modes_risk_hull(struct __private__FfiSlice lats, struct __private__FfiSlice lons, int64_t count, double pad_meters);
double __swift_bridge__$flows_modes_amtrak_fare(double miles);
double __swift_bridge__$flows_modes_greyhound_fare(double miles);
void* __swift_bridge__$flows_modes_local_fares(void);
double __swift_bridge__$flows_modes_ride_cost(double miles);
bool __swift_bridge__$flows_modes_meets_bar(double walk_alone_seconds, double total_seconds, double cost_usd);
struct __swift_bridge__$FlowsModesRideOffer __swift_bridge__$flows_modes_evaluate_ride(double walk_alone_seconds, double drive_seconds, double trip_miles);
void* __swift_bridge__$flows_modes_prefix_coordinates(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double meters);
void* __swift_bridge__$flows_modes_ride_constants(void);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsPlacesNearest { bool has; int64_t index; double off_route; } __swift_bridge__$FlowsPlacesNearest;
typedef struct __swift_bridge__$Option$FlowsPlacesNearest { bool is_some; __swift_bridge__$FlowsPlacesNearest val; } __swift_bridge__$Option$FlowsPlacesNearest;
typedef struct __swift_bridge__$FlowsPlacesCellKey { bool has; int64_t key; } __swift_bridge__$FlowsPlacesCellKey;
typedef struct __swift_bridge__$Option$FlowsPlacesCellKey { bool is_some; __swift_bridge__$FlowsPlacesCellKey val; } __swift_bridge__$Option$FlowsPlacesCellKey;
typedef struct __swift_bridge__$FlowsPlacesKindPolicy { bool has; double max_detour_meters; double max_detour_trucker_meters; double region_meters; uint32_t shard_groups; bool closed_fallback; bool empty_fallback; bool habit_pins; bool nearest_leads; bool ratings_lookup; bool brand_cost_tier; bool shower_ladder; bool location_dedup; } __swift_bridge__$FlowsPlacesKindPolicy;
typedef struct __swift_bridge__$Option$FlowsPlacesKindPolicy { bool is_some; __swift_bridge__$FlowsPlacesKindPolicy val; } __swift_bridge__$Option$FlowsPlacesKindPolicy;
typedef struct __swift_bridge__$FlowsPlacesLimits { double backtrack_tolerance_meters; double max_detour_meters; double detour_speed_mps; double dollars_per_hour; double average_nightly_price; int64_t ranked_rows; int64_t instant_rows; int64_t fallback_rows; int64_t search_enough_hits; int64_t named_enough_hits; int64_t named_centers; double named_region_meters; } __swift_bridge__$FlowsPlacesLimits;
typedef struct __swift_bridge__$Option$FlowsPlacesLimits { bool is_some; __swift_bridge__$FlowsPlacesLimits val; } __swift_bridge__$Option$FlowsPlacesLimits;
typedef struct FlowsPlacesIndex FlowsPlacesIndex;
void __swift_bridge__$FlowsPlacesIndex$_free(void* self);

void* __swift_bridge__$Vec_FlowsPlacesIndex$new(void);
void __swift_bridge__$Vec_FlowsPlacesIndex$drop(void* vec_ptr);
void __swift_bridge__$Vec_FlowsPlacesIndex$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FlowsPlacesIndex$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsPlacesIndex$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FlowsPlacesIndex$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FlowsPlacesIndex$len(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsPlacesIndex$as_ptr(void* vec_ptr);

typedef struct FlowsRoutePath FlowsRoutePath;
void __swift_bridge__$FlowsRoutePath$_free(void* self);

void* __swift_bridge__$Vec_FlowsRoutePath$new(void);
void __swift_bridge__$Vec_FlowsRoutePath$drop(void* vec_ptr);
void __swift_bridge__$Vec_FlowsRoutePath$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FlowsRoutePath$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsRoutePath$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FlowsRoutePath$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FlowsRoutePath$len(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsRoutePath$as_ptr(void* vec_ptr);

void* __swift_bridge__$flows_places_route_path(struct __private__FfiSlice lats, struct __private__FfiSlice lons);
void* __swift_bridge__$flows_places_route_path_empty(void);
void* __swift_bridge__$FlowsRoutePath$cumulative(void* self);
struct __swift_bridge__$FlowsPlacesNearest __swift_bridge__$FlowsRoutePath$nearest(void* self, double lat, double lon);
void* __swift_bridge__$FlowsRoutePath$annotate(void* self, double lat, double lon, double vehicle_along);
void* __swift_bridge__$FlowsRoutePath$rank_along(void* self, uint8_t kind, bool has_fuel, uint8_t fuel, bool trucker, bool has_position, double lat, double lon, struct __private__FfiSlice item_lats, struct __private__FfiSlice item_lons, struct __private__FfiSlice prices, struct __private__FfiSlice has_price, struct __private__FfiSlice ratings, struct __private__FfiSlice has_rating, struct RustStr names_joined, struct __private__FfiSlice name_lens, struct __private__FfiSlice name_present);
int64_t __swift_bridge__$flows_places_route_decimation_step(int64_t count);
bool __swift_bridge__$flows_places_admissible(double ahead_meters, double detour_meters, double max_detour);
void* __swift_bridge__$flows_places_rank_food(struct __private__FfiSlice ahead, struct __private__FfiSlice detour, struct __private__FfiSlice prices, struct __private__FfiSlice has_price, struct __private__FfiSlice ratings, struct __private__FfiSlice has_rating, double max_detour);
void* __swift_bridge__$flows_places_rank_fuel(struct __private__FfiSlice ahead, struct __private__FfiSlice detour, struct __private__FfiSlice prices, struct __private__FfiSlice has_price, struct __private__FfiSlice ratings, struct __private__FfiSlice has_rating, double fill_units, double average_price_per_unit, double max_detour);
void* __swift_bridge__$flows_places_rank_hotels(struct __private__FfiSlice ahead, struct __private__FfiSlice detour, struct __private__FfiSlice prices, struct __private__FfiSlice has_price, struct __private__FfiSlice ratings, struct __private__FfiSlice has_rating, double average_nightly, double max_detour);
void* __swift_bridge__$flows_places_rank_parking(struct __private__FfiSlice ahead, struct __private__FfiSlice detour, struct __private__FfiSlice prices, struct __private__FfiSlice has_price, struct __private__FfiSlice ratings, struct __private__FfiSlice has_rating, struct __private__FfiSlice cost_tiers, double max_detour);
void* __swift_bridge__$flows_places_rank_stores(struct __private__FfiSlice ahead, struct __private__FfiSlice detour, struct __private__FfiSlice prices, struct __private__FfiSlice has_price, struct __private__FfiSlice ratings, struct __private__FfiSlice has_rating, struct __private__FfiSlice market_ranks, double max_detour);
int64_t __swift_bridge__$flows_places_parking_cost_tier(struct RustStr name, bool has_name);
int64_t __swift_bridge__$flows_places_store_market_share_rank(struct RustStr name, bool has_name);
void* __swift_bridge__$flows_places_store_market_share_order(void);
double __swift_bridge__$flows_places_fuel_fill_units(uint8_t fuel);
double __swift_bridge__$flows_places_fuel_average_price(uint8_t fuel);
struct __swift_bridge__$FlowsPlacesLimits __swift_bridge__$flows_places_limits(void);
struct __swift_bridge__$FlowsPlacesKindPolicy __swift_bridge__$flows_places_kind_policy(uint8_t kind);
int64_t __swift_bridge__$flows_places_search_center_cap(int64_t query_count);
void* __swift_bridge__$flows_places_center_picks(int64_t count, int64_t cap);
int64_t __swift_bridge__$flows_places_first_nearest(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon);
void* __swift_bridge__$flows_places_rank_by_distance(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double lat, double lon, int64_t limit);
void* __swift_bridge__$flows_places_attribute_id(struct RustStr name, double latitude, double longitude);
void* __swift_bridge__$flows_places_dedup(bool location_only, struct RustStr names_joined, struct __private__FfiSlice name_lens, struct __private__FfiSlice name_present, struct __private__FfiSlice lats, struct __private__FfiSlice lons);
void* __swift_bridge__$flows_places_pinned(struct RustStr keys_joined, struct __private__FfiSlice key_lens, int64_t everyday_count, int64_t closed_count, int64_t ranked_count);
void* __swift_bridge__$flows_places_merge(struct RustStr keys_joined, struct __private__FfiSlice key_lens, int64_t everyday_count, int64_t network_count);
uint8_t __swift_bridge__$flows_places_shower_brand(struct RustStr name);
bool __swift_bridge__$flows_places_truck_parking_admissible(struct RustStr name);
void* __swift_bridge__$flows_places_index_parse(struct __private__FfiSlice data);
struct __swift_bridge__$FlowsPlacesCellKey __swift_bridge__$flows_places_cell_key(int64_t lat5, int64_t lon5);
int64_t __swift_bridge__$FlowsPlacesIndex$count(void* self);
void* __swift_bridge__$FlowsPlacesIndex$places_near(void* self, struct __private__FfiSlice data, double lat, double lon, struct __private__FfiSlice groups, double radius_meters, int64_t limit);
void* __swift_bridge__$FlowsPlacesIndex$place_numbers(void* self, struct __private__FfiSlice data, int64_t index);
void* __swift_bridge__$FlowsPlacesIndex$place_texts(void* self, struct __private__FfiSlice data, int64_t index);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsPlacesTextOptional { double is_some; double value; } __swift_bridge__$FlowsPlacesTextOptional;
typedef struct __swift_bridge__$Option$FlowsPlacesTextOptional { bool is_some; __swift_bridge__$FlowsPlacesTextOptional val; } __swift_bridge__$Option$FlowsPlacesTextOptional;
typedef struct __swift_bridge__$FlowsPlacesTextPrices { double has; double gas; double diesel; } __swift_bridge__$FlowsPlacesTextPrices;
typedef struct __swift_bridge__$Option$FlowsPlacesTextPrices { bool is_some; __swift_bridge__$FlowsPlacesTextPrices val; } __swift_bridge__$Option$FlowsPlacesTextPrices;
int64_t __swift_bridge__$flows_places_text_cost_tier(struct RustStr name);
void* __swift_bridge__$flows_places_text_website(struct RustStr name);
int32_t __swift_bridge__$flows_places_text_gym_has_showers(struct RustStr name);
int32_t __swift_bridge__$flows_places_text_parking_fee(struct RustStr name);
uint8_t __swift_bridge__$flows_places_text_shelter_type(struct RustStr name, struct RustStr query);
bool __swift_bridge__$flows_places_text_is_shelter_noise(struct RustStr name);
bool __swift_bridge__$flows_places_text_asked_name_matches(struct RustStr asked, struct RustStr name);
uint8_t __swift_bridge__$flows_places_text_country_for_coordinate(double latitude, double longitude);
void* __swift_bridge__$flows_places_text_check_breakpoints(uint8_t country);
int64_t __swift_bridge__$flows_places_text_cost_tier_for_check(double average_check, uint8_t country);
double __swift_bridge__$flows_places_text_estimated_nightly(int64_t cost_tier, bool has_tier);
int64_t __swift_bridge__$flows_places_text_yelp_cost_tier(struct RustStr price, double rating, bool has_rating);
uint8_t __swift_bridge__$flows_places_text_shower_for_name(struct RustStr name, bool has_name);
uint8_t __swift_bridge__$flows_places_text_shower_ladder(struct RustStr name, bool has_name, bool has_position, bool disproved, struct RustStr tag, bool has_tag);
int64_t __swift_bridge__$flows_places_text_shower_table_entry(struct __private__FfiSlice lats, struct __private__FfiSlice lons, double latitude, double longitude);
void* __swift_bridge__$flows_places_text_city_keys(struct RustStr state, struct RustStr city);
void* __swift_bridge__$flows_places_text_lowercased(struct RustStr text);
void* __swift_bridge__$flows_places_text_uppercased(struct RustStr text);
double __swift_bridge__$flows_places_text_national_gas(void);
double __swift_bridge__$flows_places_text_national_diesel(void);
double __swift_bridge__$flows_places_text_national_kwh(void);
double __swift_bridge__$flows_places_text_mxn_per_usd(void);
double __swift_bridge__$flows_places_text_liters_per_gallon(void);
double __swift_bridge__$flows_places_text_usd_per_gallon(double mxn_per_liter);
double __swift_bridge__$flows_places_text_mexico_estimate(uint8_t fuel);
void* __swift_bridge__$flows_places_text_fuel_state_code(struct RustStr state, bool has_state);
double __swift_bridge__$flows_places_text_fuel_estimate(uint8_t fuel, struct RustStr code, bool has_code, double live_gas, double live_diesel, bool has_live);
struct __swift_bridge__$FlowsPlacesTextPrices __swift_bridge__$flows_places_text_parse_current_avg(struct RustStr html);
void* __swift_bridge__$flows_places_text_state_names(void);
void* __swift_bridge__$flows_places_text_state_codes(void);
void* __swift_bridge__$flows_places_text_parse_turn_lanes(struct RustStr turn_lanes);
uint8_t __swift_bridge__$flows_places_text_turn_side(uint8_t turn);
bool __swift_bridge__$flows_places_text_lane_allows(struct __private__FfiSlice turns, uint8_t side);
void* __swift_bridge__$flows_places_text_recommended_lanes(struct __private__FfiSlice lanes_flat, uint8_t side);
int32_t __swift_bridge__$flows_places_text_camera_kind(struct RustStr highway, struct RustStr enforcement, struct RustStr traffic_signals, struct RustStr red_light_camera);
struct __swift_bridge__$FlowsPlacesTextOptional __swift_bridge__$flows_places_text_camera_limit_mph(struct RustStr maxspeed, bool has_maxspeed);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsRidesPoint { bool has; double lat; double lon; } __swift_bridge__$FlowsRidesPoint;
typedef struct __swift_bridge__$Option$FlowsRidesPoint { bool is_some; __swift_bridge__$FlowsRidesPoint val; } __swift_bridge__$Option$FlowsRidesPoint;
typedef struct __swift_bridge__$FlowsRidesPosition { bool has; double lat; double lon; bool exact; } __swift_bridge__$FlowsRidesPosition;
typedef struct __swift_bridge__$Option$FlowsRidesPosition { bool is_some; __swift_bridge__$FlowsRidesPosition val; } __swift_bridge__$Option$FlowsRidesPosition;
struct __swift_bridge__$FlowsRidesPoint __swift_bridge__$flows_rides_parse_coordinate(struct RustStr text);
int64_t __swift_bridge__$flows_rides_recents_cap(void);
double __swift_bridge__$flows_rides_recent_score(int64_t uses, double last_used, double now);
void* __swift_bridge__$flows_rides_recordable_name(struct RustStr name);
void* __swift_bridge__$flows_rides_merged_recents(struct RustStr names, struct __private__FfiSlice name_lengths, struct __private__FfiSlice last_used, struct __private__FfiSlice uses, int64_t count, struct RustStr new_name, double new_last_used, int64_t new_uses, double now);
void* __swift_bridge__$flows_rides_matching_recents(struct RustStr names, struct __private__FfiSlice name_lengths, int64_t count, struct RustStr fragment, int64_t limit);
void* __swift_bridge__$flows_rides_blend_suggestions(struct RustStr pinned, struct __private__FfiSlice pinned_lengths, int64_t pinned_count, struct RustStr completions, struct __private__FfiSlice completion_lengths, int64_t completion_count, int64_t cap);
double __swift_bridge__$flows_rides_ride_multiplier(struct RustStr mode);
double __swift_bridge__$flows_rides_fallback_mph(struct RustStr mode);
double __swift_bridge__$flows_rides_ride_duration(struct RustStr mode, double drive_seconds, bool has_drive, double miles);
void* __swift_bridge__$flows_rides_rental_brands(void);
void* __swift_bridge__$flows_rides_rental_brand_lengths(void);
int64_t __swift_bridge__$flows_rides_rental_brand_rank(struct RustStr name, bool has_name);
void* __swift_bridge__$flows_rides_rental_booking_site(struct RustStr name, bool has_name);
void* __swift_bridge__$flows_rides_recommend_rentals(struct RustStr names, struct __private__FfiSlice name_lengths, struct __private__FfiSlice miles, int64_t count, int64_t limit);
uint8_t __swift_bridge__$flows_rides_radio_purpose(struct RustStr channel);
bool __swift_bridge__$flows_rides_radio_is_car_band(struct RustStr channel);
int64_t __swift_bridge__$flows_rides_radio_advance(int64_t index, int64_t count, int64_t step);
void* __swift_bridge__$flows_rides_radio_state_code(struct RustStr name);
struct __swift_bridge__$FlowsRidesPosition __swift_bridge__$flows_rides_radio_position(struct RustStr name, double lat, bool has_lat, double lon, bool has_lon);
void* __swift_bridge__$flows_rides_relay_channels(struct RustStr html, struct RustStr names, struct __private__FfiSlice name_lengths, struct __private__FfiSlice located, int64_t count);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
double __swift_bridge__$flows_risk_green_min(void);
double __swift_bridge__$flows_risk_yellow_min(void);
double __swift_bridge__$flows_risk_red_min(void);
double __swift_bridge__$flows_secondary_ceiling(void);
double __swift_bridge__$flows_acute_nudge(void);
void* __swift_bridge__$flows_primary_families(void);
void* __swift_bridge__$flows_secondary_families(void);
void* __swift_bridge__$flows_acute_families(void);
void* __swift_bridge__$flows_weighted_family_names(void);
void* __swift_bridge__$flows_weighted_family_values(void);
uint8_t __swift_bridge__$flows_risk_band_code(double score);
double __swift_bridge__$flows_piecewise_score(double value, double low, double medium, double high);
double __swift_bridge__$flows_temperature_risk(double temp_f, double comfort_low_f, double comfort_high_f, double record_low_f, double record_high_f);
bool __swift_bridge__$flows_temperature_anomalous(double temp_f, double comfort_low_f, double comfort_high_f, double record_low_f, double record_high_f);
double __swift_bridge__$flows_wind_risk(double mph);
double __swift_bridge__$flows_pop_risk(double pct);
double __swift_bridge__$flows_forecast_composite(double temp, double wind, double pop);
double __swift_bridge__$flows_noisy_or_named(struct RustStr names, struct __private__FfiSlice scores);
double __swift_bridge__$flows_realized_risk_dense(struct __private__FfiSlice scores);
double __swift_bridge__$flows_flood_elevation_multiplier(double sample_elevation, bool has_sample_elevation, double local_min_elevation, bool has_local_min_elevation, double qpf_inches, bool has_qpf_inches, double supporting_evidence);
double __swift_bridge__$flows_ranking_risk(double band, double zip_exposure, double seasonal_prior, double prior_confidence);
int32_t __swift_bridge__$flows_alert_family_index(struct RustStr event);
int32_t __swift_bridge__$flows_peak_family_position(struct RustStr names, struct __private__FfiSlice scores, double floor);
int32_t __swift_bridge__$flows_dominant_family_position(struct RustStr names, struct __private__FfiSlice scores, double floor);
double __swift_bridge__$flows_displayed_band(double weighted, double peak);
double __swift_bridge__$flows_ahead_display_risk(struct __private__FfiSlice sample_risks, struct __private__FfiSlice seg_lengths, double along_meters);
void* __swift_bridge__$flows_decode_polyline_lonlat(struct __private__FfiSlice bytes);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct FlowsRiskField FlowsRiskField;
void __swift_bridge__$FlowsRiskField$_free(void* self);

void* __swift_bridge__$Vec_FlowsRiskField$new(void);
void __swift_bridge__$Vec_FlowsRiskField$drop(void* vec_ptr);
void __swift_bridge__$Vec_FlowsRiskField$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FlowsRiskField$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsRiskField$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FlowsRiskField$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FlowsRiskField$len(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsRiskField$as_ptr(void* vec_ptr);

void* __swift_bridge__$flows_risk_field_parse_frb1(struct __private__FfiSlice data);
void* __swift_bridge__$flows_risk_field_empty(struct RustStr generated, struct RustStr families_joined, struct __private__FfiSlice family_lens, int64_t family_count);
void* __swift_bridge__$flows_risk_field_from_columns(struct RustStr generated, struct RustStr families_joined, struct __private__FfiSlice family_lens, int64_t family_count, struct RustStr zips_joined, struct __private__FfiSlice zip_lens, struct __private__FfiSlice lats, struct __private__FfiSlice lons, struct __private__FfiSlice score_counts, struct __private__FfiSlice scores, struct RustStr summaries_joined, struct __private__FfiSlice summary_lens, struct __private__FfiSlice has_summary, struct __private__FfiSlice ring_counts, struct __private__FfiSlice has_ring, struct __private__FfiSlice ring_points);
void* __swift_bridge__$FlowsRiskField$generated(void* self);
void* __swift_bridge__$FlowsRiskField$families(void* self);
int64_t __swift_bridge__$FlowsRiskField$family_index(void* self, struct RustStr family);
int64_t __swift_bridge__$FlowsRiskField$count(void* self);
void* __swift_bridge__$FlowsRiskField$zip(void* self, int64_t index);
double __swift_bridge__$FlowsRiskField$latitude(void* self, int64_t index);
double __swift_bridge__$FlowsRiskField$longitude(void* self, int64_t index);
void* __swift_bridge__$FlowsRiskField$scores(void* self, int64_t index);
bool __swift_bridge__$FlowsRiskField$has_summary(void* self, int64_t index);
void* __swift_bridge__$FlowsRiskField$summary(void* self, int64_t index);
bool __swift_bridge__$FlowsRiskField$has_ring(void* self, int64_t index);
void* __swift_bridge__$FlowsRiskField$ring(void* self, int64_t index);
int64_t __swift_bridge__$FlowsRiskField$nearest(void* self, double latitude, double longitude);
void* __swift_bridge__$FlowsRiskField$select(void* self, double lat_min, double lat_max, double lon_min, double lon_max, int64_t family_index, int64_t limit);
int64_t __swift_bridge__$FlowsRiskField$harmonic_rescore(void* self, void* table, int64_t week);
void* __swift_bridge__$flows_risk_summary_plain(struct RustStr text);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsSeasonalOptional { double is_some; double value; } __swift_bridge__$FlowsSeasonalOptional;
typedef struct __swift_bridge__$Option$FlowsSeasonalOptional { bool is_some; __swift_bridge__$FlowsSeasonalOptional val; } __swift_bridge__$Option$FlowsSeasonalOptional;
typedef struct __swift_bridge__$FlowsSeasonalWeekStat { double w_sum; double w_observed; double w_sq_err; double last_t; int64_t count; } __swift_bridge__$FlowsSeasonalWeekStat;
typedef struct __swift_bridge__$Option$FlowsSeasonalWeekStat { bool is_some; __swift_bridge__$FlowsSeasonalWeekStat val; } __swift_bridge__$Option$FlowsSeasonalWeekStat;
typedef struct __swift_bridge__$FlowsSeasonalPrior { double has; double risk; double confidence; } __swift_bridge__$FlowsSeasonalPrior;
typedef struct __swift_bridge__$Option$FlowsSeasonalPrior { bool is_some; __swift_bridge__$FlowsSeasonalPrior val; } __swift_bridge__$Option$FlowsSeasonalPrior;
typedef struct __swift_bridge__$FlowsSeasonalOriginStat { double weighted; double last_seen; double first_seen; int64_t trips; } __swift_bridge__$FlowsSeasonalOriginStat;
typedef struct __swift_bridge__$Option$FlowsSeasonalOriginStat { bool is_some; __swift_bridge__$FlowsSeasonalOriginStat val; } __swift_bridge__$Option$FlowsSeasonalOriginStat;
typedef struct __swift_bridge__$FlowsSeasonalCell { double has; int64_t lat; int64_t lon; } __swift_bridge__$FlowsSeasonalCell;
typedef struct __swift_bridge__$Option$FlowsSeasonalCell { bool is_some; __swift_bridge__$FlowsSeasonalCell val; } __swift_bridge__$Option$FlowsSeasonalCell;
typedef struct __swift_bridge__$FlowsSeasonalHome { double has; double lat; double lon; int64_t trips; } __swift_bridge__$FlowsSeasonalHome;
typedef struct __swift_bridge__$Option$FlowsSeasonalHome { bool is_some; __swift_bridge__$FlowsSeasonalHome val; } __swift_bridge__$Option$FlowsSeasonalHome;
double __swift_bridge__$flows_seasonal_cross_country_km(void);
int64_t __swift_bridge__$flows_seasonal_local_trip_threshold(void);
int64_t __swift_bridge__$flows_seasonal_cross_country_trip_threshold(void);
double __swift_bridge__$flows_seasonal_min_week_samples_for_confidence(void);
double __swift_bridge__$flows_seasonal_decay_half_life_weeks(void);
int64_t __swift_bridge__$flows_seasonal_home_min_trips(void);
int64_t __swift_bridge__$flows_seasonal_max_edges(void);
int64_t __swift_bridge__$flows_seasonal_max_origins(void);
double __swift_bridge__$flows_seasonal_origin_half_life_days(void);
double __swift_bridge__$flows_seasonal_relocation_margin(void);
double __swift_bridge__$flows_seasonal_relocation_min_days(void);
int64_t __swift_bridge__$flows_seasonal_route_feature_count(void);
int64_t __swift_bridge__$flows_seasonal_tune_epochs(void);
double __swift_bridge__$flows_seasonal_tune_learning_rate(void);
double __swift_bridge__$flows_seasonal_tune_anchor(void);
int64_t __swift_bridge__$flows_seasonal_tune_min_trips(void);
double __swift_bridge__$flows_seasonal_tune_min_interval_seconds(void);
int64_t __swift_bridge__$flows_seasonal_tune_min_new_trips(void);
struct __swift_bridge__$FlowsSeasonalWeekStat __swift_bridge__$flows_seasonal_week_stat_decayed(struct __swift_bridge__$FlowsSeasonalWeekStat stat, double t, double half_life_weeks);
struct __swift_bridge__$FlowsSeasonalWeekStat __swift_bridge__$flows_seasonal_week_stat_added(struct __swift_bridge__$FlowsSeasonalWeekStat stat, double observed, double predicted, double t, double half_life_weeks);
double __swift_bridge__$flows_seasonal_mean_observed(double w_sum, double w_observed);
bool __swift_bridge__$flows_seasonal_is_modeled(int64_t trip_count, bool cross_country);
bool __swift_bridge__$flows_seasonal_is_cross_country(double distance_km);
int64_t __swift_bridge__$flows_seasonal_next_count(int64_t count);
void* __swift_bridge__$flows_seasonal_prior_week_keys(int64_t week);
struct __swift_bridge__$FlowsSeasonalPrior __swift_bridge__$flows_seasonal_prior(int64_t trip_count, bool cross_country, int64_t week, struct __private__FfiSlice cells, struct __private__FfiSlice present, double now);
struct __swift_bridge__$FlowsSeasonalOptional __swift_bridge__$flows_seasonal_accuracy(int64_t trip_count, struct __private__FfiSlice stats, double now);
struct __swift_bridge__$FlowsSeasonalOptional __swift_bridge__$flows_seasonal_mean_in_order(struct __private__FfiSlice values);
void* __swift_bridge__$flows_seasonal_training_rows(struct __private__FfiSlice cells, double now);
struct __swift_bridge__$FlowsSeasonalOptional __swift_bridge__$flows_seasonal_route_cell(double degrees);
double __swift_bridge__$flows_seasonal_route_cell_degrees(int64_t cell);
void* __swift_bridge__$flows_seasonal_path_edge_keys(struct __private__FfiSlice hubs);
void* __swift_bridge__$flows_seasonal_origin_key(int64_t lat, int64_t lon);
struct __swift_bridge__$FlowsSeasonalCell __swift_bridge__$flows_seasonal_parse_origin_key(struct RustStr key);
double __swift_bridge__$flows_seasonal_origin_decayed(double weighted, double last_seen, double now);
struct __swift_bridge__$FlowsSeasonalOriginStat __swift_bridge__$flows_seasonal_origin_after_trip(struct __swift_bridge__$FlowsSeasonalOriginStat prior, double t);
bool __swift_bridge__$flows_seasonal_origins_over_cap(int64_t count);
void* __swift_bridge__$flows_seasonal_origin_evictions(struct __private__FfiSlice stats, double now);
double __swift_bridge__$flows_seasonal_edge_freshness(struct __private__FfiSlice last_ts);
bool __swift_bridge__$flows_seasonal_edges_over_cap(int64_t count);
void* __swift_bridge__$flows_seasonal_edge_evictions(struct __private__FfiSlice freshness);
struct __swift_bridge__$FlowsSeasonalHome __swift_bridge__$flows_seasonal_learned_home(struct __private__FfiSlice entries, double now, int64_t current_lat, int64_t current_lon, bool has_current);
struct __swift_bridge__$FlowsSeasonalHome __swift_bridge__$flows_seasonal_legacy_home(struct __private__FfiSlice routes);
void* __swift_bridge__$flows_seasonal_route_features(double o_lat, double o_lon, double d_lat, double d_lon, int64_t week, bool cross_country);
double __swift_bridge__$flows_seasonal_head_predict(struct __private__FfiSlice buffer);
void* __swift_bridge__$flows_seasonal_fine_tune(struct __private__FfiSlice head, struct __private__FfiSlice rows, int64_t epochs, double learning_rate, double anchor);
struct __swift_bridge__$FlowsSeasonalOptional __swift_bridge__$flows_seasonal_mean_squared_error(struct __private__FfiSlice head, struct __private__FfiSlice rows);
int64_t __swift_bridge__$flows_seasonal_tuned_rows(int64_t base_rows, bool has_base_rows, int64_t samples);
uint8_t __swift_bridge__$flows_seasonal_choose_head(bool has_local, int64_t local_rows, bool has_local_rows, bool local_tuned, bool has_local_tuned, bool has_bundled, int64_t bundled_rows, bool has_bundled_rows);
bool __swift_bridge__$flows_seasonal_tune_due(int64_t total_trips, double seconds_since_last_tune, bool has_last_tune, int64_t tuned_at_trip_count);
bool __swift_bridge__$flows_seasonal_accept_tune(double tuned_mse, double base_mse);
double __swift_bridge__$flows_seasonal_blend_prior(double modeled, double observed_risk, double confidence);
int64_t __swift_bridge__$flows_seasonal_week_of_year(int64_t ordinal_day, bool has_ordinal_day);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsTagsNumber { bool has; double value; } __swift_bridge__$FlowsTagsNumber;
typedef struct __swift_bridge__$Option$FlowsTagsNumber { bool is_some; __swift_bridge__$FlowsTagsNumber val; } __swift_bridge__$Option$FlowsTagsNumber;
typedef struct __swift_bridge__$FlowsTagsOutcome { uint8_t code; int64_t index; } __swift_bridge__$FlowsTagsOutcome;
typedef struct __swift_bridge__$Option$FlowsTagsOutcome { bool is_some; __swift_bridge__$FlowsTagsOutcome val; } __swift_bridge__$Option$FlowsTagsOutcome;
struct __swift_bridge__$FlowsTagsNumber __swift_bridge__$flows_tags_max_grade_percent(struct __private__FfiSlice elevations, struct __private__FfiSlice present, int64_t count, double spacing_meters);
struct __swift_bridge__$FlowsTagsNumber __swift_bridge__$flows_tags_clearance_meters(struct RustStr tag);
struct __swift_bridge__$FlowsTagsNumber __swift_bridge__$flows_tags_weight_limit_lbs(struct RustStr tag);
bool __swift_bridge__$flows_tags_is_high_risk_flood_zone(struct RustStr zone);
void* __swift_bridge__$flows_tags_route_constants(void);
void* __swift_bridge__$flows_tags_limits_on_route(struct __private__FfiSlice route_lats, struct __private__FfiSlice route_lons, struct __private__FfiSlice way_point_counts, struct __private__FfiSlice way_lats, struct __private__FfiSlice way_lons, struct RustStr way_tags_joined, struct __private__FfiSlice way_tag_lens);
void* __swift_bridge__$flows_tags_parse_tpms(struct RustStr name, bool has_name, struct __private__FfiSlice data, int64_t data_count, bool has_data);
void* __swift_bridge__$flows_tags_tpms_position(struct RustStr name);
double __swift_bridge__$flows_tags_displayed_psi(double psi);
struct __swift_bridge__$FlowsTagsNumber __swift_bridge__$flows_tags_parse_fuel_reply(struct RustStr line);
bool __swift_bridge__$flows_tags_looks_like_obd_adapter(struct RustStr name);
double __swift_bridge__$flows_tags_low_pressure_psi(void);
int64_t __swift_bridge__$flows_tags_interpret_yes_no(struct RustStr transcript);
bool __swift_bridge__$flows_tags_wants_weather_radio(struct RustStr transcript);
struct __swift_bridge__$FlowsTagsOutcome __swift_bridge__$flows_tags_choose(struct RustStr reply, struct RustStr options, struct __private__FfiSlice option_lengths, int64_t option_count);
struct __swift_bridge__$FlowsTagsOutcome __swift_bridge__$flows_tags_place_reply(struct RustStr reply, struct RustStr places, struct __private__FfiSlice place_lengths, int64_t place_count, struct RustStr cuisines, struct __private__FfiSlice cuisine_lengths, int64_t cuisine_count);
void* __swift_bridge__$flows_tags_list_text(uint16_t list);
void* __swift_bridge__$flows_tags_list_lengths(uint16_t list);
int64_t __swift_bridge__$flows_tags_kind_for_tags(struct RustStr tags);
void* __swift_bridge__$flows_tags_match_order(void);
void* __swift_bridge__$flows_tags_dial_label(struct RustStr name);
void* __swift_bridge__$flows_tags_ranked_stations(struct __private__FfiSlice lats, struct __private__FfiSlice has_lat, struct __private__FfiSlice lons, struct __private__FfiSlice has_lon, struct __private__FfiSlice bitrates, int64_t count, double lat, double lon, bool has_position);
bool __swift_bridge__$flows_tags_is_allowed_mirror(struct RustStr host);
int64_t __swift_bridge__$flows_tags_nearby_radius_meters(void);
void* __swift_bridge__$flows_tags_merged_stations(struct RustStr names, struct __private__FfiSlice name_lengths, struct RustStr urls, struct __private__FfiSlice url_lengths, int64_t name_hit_count, bool has_name_hits, int64_t tag_hit_count, bool has_tag_hits);
void* __swift_bridge__$flows_tags_kept_station_rows(struct RustStr names, struct __private__FfiSlice name_lengths, struct __private__FfiSlice has_name, struct RustStr urls, struct __private__FfiSlice url_lengths, struct __private__FfiSlice has_url, int64_t count);
void* __swift_bridge__$flows_tags_station_name(struct RustStr name);
void* __swift_bridge__$flows_tags_unique_server_names(struct RustStr names, struct __private__FfiSlice lengths, struct __private__FfiSlice present, int64_t count);
void* __swift_bridge__$flows_tags_genre_words(struct RustStr tags);
void* __swift_bridge__$flows_tags_state_name(struct RustStr code);
void* __swift_bridge__$flows_tags_ranked_nearest(struct __private__FfiSlice lats, struct __private__FfiSlice has_lat, struct __private__FfiSlice lons, struct __private__FfiSlice has_lon, struct __private__FfiSlice votes, struct RustStr urls, struct __private__FfiSlice url_lengths, int64_t count, double lat, double lon);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$TripVehicleOptional { double is_some; double value; } __swift_bridge__$TripVehicleOptional;
typedef struct __swift_bridge__$Option$TripVehicleOptional { bool is_some; __swift_bridge__$TripVehicleOptional val; } __swift_bridge__$Option$TripVehicleOptional;
typedef struct __swift_bridge__$TripVehicleHosStatus { double code; double seconds_until_due; } __swift_bridge__$TripVehicleHosStatus;
typedef struct __swift_bridge__$Option$TripVehicleHosStatus { bool is_some; __swift_bridge__$TripVehicleHosStatus val; } __swift_bridge__$Option$TripVehicleHosStatus;
typedef struct __swift_bridge__$TripVehicleHabits { double miles_since_fill; double average_speed_mph; double idle_fraction; } __swift_bridge__$TripVehicleHabits;
typedef struct __swift_bridge__$Option$TripVehicleHabits { bool is_some; __swift_bridge__$TripVehicleHabits val; } __swift_bridge__$Option$TripVehicleHabits;
typedef struct __swift_bridge__$TripVehicleClassPhysical { double tank; double height; double gvwr; double tow_capacity; } __swift_bridge__$TripVehicleClassPhysical;
typedef struct __swift_bridge__$Option$TripVehicleClassPhysical { bool is_some; __swift_bridge__$TripVehicleClassPhysical val; } __swift_bridge__$Option$TripVehicleClassPhysical;
void* __swift_bridge__$flows_trip_vehicle_fuel_type_names(void);
void* __swift_bridge__$flows_trip_vehicle_food_category_names(void);
void* __swift_bridge__$flows_trip_vehicle_need_label(uint8_t code);
double __swift_bridge__$flows_trip_vehicle_default_miles_per_unit(void);
uint8_t __swift_bridge__$flows_trip_vehicle_default_fuel_code(void);
double __swift_bridge__$flows_trip_vehicle_grams_co2_per_unit(uint8_t fuel);
double __swift_bridge__$flows_trip_vehicle_transit_grams_co2_per_mile(bool rail, bool long_haul);
struct __swift_bridge__$TripVehicleOptional __swift_bridge__$flows_trip_vehicle_drive_fuel_cost_usd(double miles, double miles_per_unit, double price_per_unit);
struct __swift_bridge__$TripVehicleOptional __swift_bridge__$flows_trip_vehicle_drive_grams_co2_per_mile(uint8_t fuel, double miles_per_unit);
void* __swift_bridge__$flows_trip_vehicle_schedule(double total_miles, struct __private__FfiSlice intervals, uint64_t seed);
int32_t __swift_bridge__$flows_trip_vehicle_next_need_index(double after_mile, struct __private__FfiSlice miles);
double __swift_bridge__$flows_trip_vehicle_adjusted_remaining_seconds(double baseline, double stop_delay_seconds);
uint64_t __swift_bridge__$flows_trip_vehicle_splitmix64_initial_state(uint64_t seed);
uint64_t __swift_bridge__$flows_trip_vehicle_splitmix64_advance(uint64_t state);
uint64_t __swift_bridge__$flows_trip_vehicle_splitmix64_mix(uint64_t state);
double __swift_bridge__$flows_trip_vehicle_impact_g_force(void);
double __swift_bridge__$flows_trip_vehicle_hard_impact_g_force(void);
double __swift_bridge__$flows_trip_vehicle_confirm_impact_g_force(void);
double __swift_bridge__$flows_trip_vehicle_min_pre_impact_speed_mps(void);
double __swift_bridge__$flows_trip_vehicle_crash_stop_speed_mps(void);
double __swift_bridge__$flows_trip_vehicle_min_speed_drop_fraction(void);
double __swift_bridge__$flows_trip_vehicle_max_meters_from_road(void);
void* __swift_bridge__$flows_trip_vehicle_assist_words(void);
void* __swift_bridge__$flows_trip_vehicle_ok_words(void);
bool __swift_bridge__$flows_trip_vehicle_is_impact_acceleration(double acceleration_g);
bool __swift_bridge__$flows_trip_vehicle_is_impact_window(struct __private__FfiSlice window);
bool __swift_bridge__$flows_trip_vehicle_is_crash(struct __private__FfiSlice window, double speed_before_mps, double speed_after_mps, double meters_from_road, bool has_meters_from_road);
int32_t __swift_bridge__$flows_trip_vehicle_interpret_reply(struct RustStr transcript);
double __swift_bridge__$flows_trip_vehicle_hos_break_due_seconds(void);
double __swift_bridge__$flows_trip_vehicle_hos_warn_before_break_seconds(void);
double __swift_bridge__$flows_trip_vehicle_hos_daily_driving_limit_seconds(void);
double __swift_bridge__$flows_trip_vehicle_hos_break_reset_seconds(void);
struct __swift_bridge__$TripVehicleHosStatus __swift_bridge__$flows_trip_vehicle_hos_status(double driving_seconds);
uint32_t __swift_bridge__$flows_trip_vehicle_spec_number_slots(void);
void* __swift_bridge__$flows_trip_vehicle_spec_makes(void);
void* __swift_bridge__$flows_trip_vehicle_spec_models(void);
void* __swift_bridge__$flows_trip_vehicle_spec_numbers(void);
void* __swift_bridge__$flows_trip_vehicle_distinct_makes(void);
void* __swift_bridge__$flows_trip_vehicle_spec_rows_for_make(struct RustStr make);
int32_t __swift_bridge__$flows_trip_vehicle_spec_index(struct RustStr make, struct RustStr model);
double __swift_bridge__$flows_trip_vehicle_minimum_height_feet(void);
double __swift_bridge__$flows_trip_vehicle_combined_miles_per_unit(double city_mpu, double highway_mpu);
double __swift_bridge__$flows_trip_vehicle_rated_miles_per_unit(double city_mpu, double highway_mpu);
double __swift_bridge__$flows_trip_vehicle_reserve_miles(void);
double __swift_bridge__$flows_trip_vehicle_efficiency_factor(double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_rated_range_miles(double tank_capacity_units, double rated_miles_per_unit);
double __swift_bridge__$flows_trip_vehicle_miles_per_unit_at_speed(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double mph);
double __swift_bridge__$flows_trip_vehicle_effective_range_miles(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_fuel_fraction_after(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double miles_since_fill, double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_expected_range_miles(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double miles_since_fill, double average_speed_mph, double idle_fraction);
bool __swift_bridge__$flows_trip_vehicle_should_recommend_fuel(double range_remaining_miles, double miles_to_next_station, double reserve_miles);
bool __swift_bridge__$flows_trip_vehicle_restore_driving_accepts(double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_restore_driving_idle(double idle_fraction);
struct __swift_bridge__$TripVehicleHabits __swift_bridge__$flows_trip_vehicle_record_fix(double miles_since_fill, double average_speed_mph, double idle_fraction, double speed_mps, double delta_meters, bool towing, double towing_economy_factor);
double __swift_bridge__$flows_trip_vehicle_store_expected_range_miles(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double miles_since_fill, double average_speed_mph, double idle_fraction, double telemetry_fuel_fraction, bool has_telemetry_fuel_fraction, bool towing, double towing_economy_factor);
struct __swift_bridge__$TripVehicleClassPhysical __swift_bridge__$flows_trip_vehicle_epa_class_physical(struct RustStr vclass);
double __swift_bridge__$flows_trip_vehicle_epa_validated_tank(double tank, double combined_mpu);
uint8_t __swift_bridge__$flows_trip_vehicle_epa_fuel_type_code(struct RustStr fuel);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
double __swift_bridge__$flows_vehicle_policy_state_tolerance_mph(void);
double __swift_bridge__$flows_vehicle_policy_excess_over_limit_mph(void);
double __swift_bridge__$flows_vehicle_policy_excess_absolute_mph(void);
double __swift_bridge__$flows_vehicle_policy_speed_sign_tolerance_mph(void);
double __swift_bridge__$flows_vehicle_policy_speed_sign_over_by_mph(void);
double __swift_bridge__$flows_vehicle_policy_pursuit_default_speed_mph(void);
double __swift_bridge__$flows_vehicle_policy_pursuit_minimum_radius_meters(void);
double __swift_bridge__$flows_vehicle_policy_pursuit_maximum_elapsed_seconds(void);
double __swift_bridge__$flows_vehicle_policy_towing_economy_factor(void);
double __swift_bridge__$flows_vehicle_policy_filter_default_vehicle_height_meters(void);
double __swift_bridge__$flows_vehicle_policy_filter_default_max_grade_percent(void);
double __swift_bridge__$flows_vehicle_policy_filter_default_clearance_margin_meters(void);
double __swift_bridge__$flows_vehicle_policy_grade_degrees(double percent);
double __swift_bridge__$flows_vehicle_policy_grade_steep_threshold_percent(void);
double __swift_bridge__$flows_vehicle_policy_grade_lookahead_miles(void);
double __swift_bridge__$flows_vehicle_policy_drive_idle_speed_mph(void);
double __swift_bridge__$flows_vehicle_policy_drive_default_efficient_cruise_mph(void);
void* __swift_bridge__$flows_vehicle_policy_compass_points(void);
double __swift_bridge__$flows_vehicle_policy_estimated_limit_mph(double speed_mph);
double __swift_bridge__$flows_vehicle_policy_effective_limit_mph(double posted_limit_mph, bool has_posted_limit_mph, double speed_mph);
double __swift_bridge__$flows_vehicle_policy_state_threshold_mph(double posted_limit_mph, bool has_posted_limit_mph);
double __swift_bridge__$flows_vehicle_policy_federal_threshold_mph(double posted_limit_mph, bool has_posted_limit_mph);
uint8_t __swift_bridge__$flows_vehicle_policy_standing_code(double speed_mph, double posted_limit_mph, bool has_posted_limit_mph);
int32_t __swift_bridge__$flows_vehicle_policy_compass_point_index(struct RustStr word);
double __swift_bridge__$flows_vehicle_policy_parse_maxspeed_mph(struct RustStr raw);
uint8_t __swift_bridge__$flows_vehicle_policy_judge_code(double speed_mph, double limit_mph, bool has_limit_mph);
double __swift_bridge__$flows_vehicle_policy_pursuit_radius_meters(double elapsed_seconds, double speed_mph);
void* __swift_bridge__$flows_vehicle_policy_towing_estimated_ratings(double height_feet, uint8_t fuel_code);
bool __swift_bridge__$flows_vehicle_policy_towing_has_effective_gcwr(bool has_gvwr_lbs, bool has_tow_capacity_lbs, bool has_gcwr_lbs);
double __swift_bridge__$flows_vehicle_policy_towing_effective_gcwr_lbs(double gvwr_lbs, bool has_gvwr_lbs, double tow_capacity_lbs, bool has_tow_capacity_lbs, double gcwr_lbs, bool has_gcwr_lbs);
void* __swift_bridge__$flows_vehicle_policy_towing_check(double vehicle_weight_lbs, double towed_weight_lbs, double gvwr_lbs, bool has_gvwr_lbs, double tow_capacity_lbs, bool has_tow_capacity_lbs, double gcwr_lbs, bool has_gcwr_lbs);
double __swift_bridge__$flows_vehicle_policy_degrees_to_percent(double degrees);
bool __swift_bridge__$flows_vehicle_policy_passes_clearances(double vehicle_height_meters, double clearance_margin_meters, struct __private__FfiSlice clearances_meters);
bool __swift_bridge__$flows_vehicle_policy_passes_grade(double max_grade_percent, double route_max_grade_percent, bool has_route_max_grade_percent);
bool __swift_bridge__$flows_vehicle_policy_passes_weight_limits(double rig_weight_lbs, bool has_rig_weight_lbs, struct __private__FfiSlice limits_lbs);
double __swift_bridge__$flows_vehicle_policy_default_max_grade_degrees(double published_max_grade_percent, bool has_published_max_grade_percent, double gvwr_lbs, bool has_gvwr_lbs, double tow_capacity_lbs, bool has_tow_capacity_lbs, double height_feet, bool towing, double trailer_weight_lbs);
void* __swift_bridge__$flows_vehicle_policy_grade_segments(struct __private__FfiSlice elevations, struct __private__FfiSlice present, double spacing_meters, double start_mile);
void* __swift_bridge__$flows_vehicle_policy_grade_steepest(struct __private__FfiSlice segments, int64_t top);
int64_t __swift_bridge__$flows_vehicle_policy_grade_next_steep_index(double mile, struct __private__FfiSlice segments, double threshold_percent, double lookahead_miles);
double __swift_bridge__$flows_vehicle_policy_drive_drag_penalty(double speed_mph, double efficient_cruise_mph);
double __swift_bridge__$flows_vehicle_policy_drive_grade_penalty(double grade_percent);
double __swift_bridge__$flows_vehicle_policy_drive_throttle_penalty(double accel_mph_per_sec);
double __swift_bridge__$flows_vehicle_policy_drive_headwind_mph(double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees);
double __swift_bridge__$flows_vehicle_policy_drive_airspeed_mph(double speed_mph, double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees);
double __swift_bridge__$flows_vehicle_policy_drive_drag_sensitivity(double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu);
double __swift_bridge__$flows_vehicle_policy_drive_load_factor(double loaded_weight_lbs, bool has_loaded_weight_lbs, double vehicle_weight_lbs, bool has_vehicle_weight_lbs, bool towing, double fuel_fraction, bool has_fuel_fraction);
double __swift_bridge__$flows_vehicle_policy_drive_score(double speed_mph, double accel_mph_per_sec, double grade_percent, double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees, double efficient_cruise_mph, double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu, double loaded_weight_lbs, bool has_loaded_weight_lbs, double vehicle_weight_lbs, bool has_vehicle_weight_lbs, bool towing, double fuel_fraction, bool has_fuel_fraction);
uint8_t __swift_bridge__$flows_vehicle_policy_drive_verdict_code(double speed_mph, double accel_mph_per_sec, double grade_percent, double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees, double efficient_cruise_mph, double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu, double loaded_weight_lbs, bool has_loaded_weight_lbs, double vehicle_weight_lbs, bool has_vehicle_weight_lbs, bool towing, double fuel_fraction, bool has_fuel_fraction);
double __swift_bridge__$flows_vehicle_policy_drive_efficient_cruise_mph(double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu);


