// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
void* __swift_bridge__$flows_alerts_display_kind_names(void);
int32_t __swift_bridge__$flows_alerts_display_kind(struct RustStr event);
int32_t __swift_bridge__$flows_alerts_display_kind_for_family(struct RustStr family);
int32_t __swift_bridge__$flows_alerts_shelter_kind(struct RustStr event, double severity_score);
bool __swift_bridge__$flows_alerts_is_life_safety(struct RustStr event);
bool __swift_bridge__$flows_alerts_is_lookout(struct RustStr event);
int32_t __swift_bridge__$flows_alerts_action(struct RustStr event, double severity_score, bool has_expiry, double seconds_until_expiry);
int32_t __swift_bridge__$flows_alerts_threat_rank(struct RustStr event, double severity_score);


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
double __swift_bridge__$flows_risk_green_min(void);
double __swift_bridge__$flows_risk_yellow_min(void);
double __swift_bridge__$flows_risk_red_min(void);
double __swift_bridge__$flows_secondary_ceiling(void);
double __swift_bridge__$flows_acute_nudge(void);
void* __swift_bridge__$flows_primary_families(void);
void* __swift_bridge__$flows_secondary_families(void);
void* __swift_bridge__$flows_acute_families(void);
void* __swift_bridge__$flows_weighted_family_names(void);
void* __swift_bridge__$flows_weighted_family_values(void);
uint8_t __swift_bridge__$flows_risk_band_code(double score);
double __swift_bridge__$flows_piecewise_score(double value, double low, double medium, double high);
double __swift_bridge__$flows_temperature_risk(double temp_f, double comfort_low_f, double comfort_high_f, double record_low_f, double record_high_f);
bool __swift_bridge__$flows_temperature_anomalous(double temp_f, double comfort_low_f, double comfort_high_f, double record_low_f, double record_high_f);
double __swift_bridge__$flows_wind_risk(double mph);
double __swift_bridge__$flows_pop_risk(double pct);
double __swift_bridge__$flows_forecast_composite(double temp, double wind, double pop);
double __swift_bridge__$flows_noisy_or_named(struct RustStr names, struct __private__FfiSlice scores);
double __swift_bridge__$flows_realized_risk_dense(struct __private__FfiSlice scores);
double __swift_bridge__$flows_flood_elevation_multiplier(double sample_elevation, bool has_sample_elevation, double local_min_elevation, bool has_local_min_elevation, double qpf_inches, bool has_qpf_inches, double supporting_evidence);
double __swift_bridge__$flows_ranking_risk(double band, double zip_exposure, double seasonal_prior, double prior_confidence);
int32_t __swift_bridge__$flows_alert_family_index(struct RustStr event);
int32_t __swift_bridge__$flows_peak_family_position(struct RustStr names, struct __private__FfiSlice scores, double floor);
int32_t __swift_bridge__$flows_dominant_family_position(struct RustStr names, struct __private__FfiSlice scores, double floor);
double __swift_bridge__$flows_displayed_band(double weighted, double peak);
void* __swift_bridge__$flows_decode_polyline_lonlat(struct __private__FfiSlice bytes);


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.


