// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
void* __swift_bridge__$flows_alerts_display_kind_names(void);
int32_t __swift_bridge__$flows_alerts_display_kind(struct RustStr event);
int32_t __swift_bridge__$flows_alerts_display_kind_for_family(struct RustStr family);
int32_t __swift_bridge__$flows_alerts_shelter_kind(struct RustStr event, double severity_score);
bool __swift_bridge__$flows_alerts_is_life_safety(struct RustStr event);
bool __swift_bridge__$flows_alerts_is_lookout(struct RustStr event);
int32_t __swift_bridge__$flows_alerts_action(struct RustStr event, double severity_score, bool has_expiry, double seconds_until_expiry);
int32_t __swift_bridge__$flows_alerts_threat_rank(struct RustStr event, double severity_score);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$FlowsClimateProfile { double has; int64_t band; double comfort_low_f; double comfort_high_f; double record_low_f; double record_high_f; double wind_low; double wind_medium; double wind_high; double pop_low; double pop_medium; double pop_high; } __swift_bridge__$FlowsClimateProfile;
typedef struct __swift_bridge__$Option$FlowsClimateProfile { bool is_some; __swift_bridge__$FlowsClimateProfile val; } __swift_bridge__$Option$FlowsClimateProfile;
typedef struct __swift_bridge__$FlowsClimateNorms { double week_low_f; double week_high_f; double wind_mean_mph; double wind_sigma_mph; } __swift_bridge__$FlowsClimateNorms;
typedef struct __swift_bridge__$Option$FlowsClimateNorms { bool is_some; __swift_bridge__$FlowsClimateNorms val; } __swift_bridge__$Option$FlowsClimateNorms;
typedef struct __swift_bridge__$FlowsClimateSolarTerms { double declination; double equation_of_time; } __swift_bridge__$FlowsClimateSolarTerms;
typedef struct __swift_bridge__$Option$FlowsClimateSolarTerms { bool is_some; __swift_bridge__$FlowsClimateSolarTerms val; } __swift_bridge__$Option$FlowsClimateSolarTerms;
typedef struct __swift_bridge__$FlowsClimateTwilight { double has; double dawn; double dusk; } __swift_bridge__$FlowsClimateTwilight;
typedef struct __swift_bridge__$Option$FlowsClimateTwilight { bool is_some; __swift_bridge__$FlowsClimateTwilight val; } __swift_bridge__$Option$FlowsClimateTwilight;
typedef struct __swift_bridge__$FlowsClimateWeekTrig { double cos_t; double sin_t; double cos_2t; double sin_2t; } __swift_bridge__$FlowsClimateWeekTrig;
typedef struct __swift_bridge__$Option$FlowsClimateWeekTrig { bool is_some; __swift_bridge__$FlowsClimateWeekTrig val; } __swift_bridge__$Option$FlowsClimateWeekTrig;
typedef struct __swift_bridge__$FlowsClimateOptional { double is_some; double value; } __swift_bridge__$FlowsClimateOptional;
typedef struct __swift_bridge__$Option$FlowsClimateOptional { bool is_some; __swift_bridge__$FlowsClimateOptional val; } __swift_bridge__$Option$FlowsClimateOptional;
typedef struct FlowsHarmonicTable FlowsHarmonicTable;
void __swift_bridge__$FlowsHarmonicTable$_free(void* self);

void* __swift_bridge__$Vec_FlowsHarmonicTable$new(void);
void __swift_bridge__$Vec_FlowsHarmonicTable$drop(void* vec_ptr);
void __swift_bridge__$Vec_FlowsHarmonicTable$push(void* vec_ptr, void* item_ptr);
void* __swift_bridge__$Vec_FlowsHarmonicTable$pop(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsHarmonicTable$get(void* vec_ptr, uintptr_t index);
void* __swift_bridge__$Vec_FlowsHarmonicTable$get_mut(void* vec_ptr, uintptr_t index);
uintptr_t __swift_bridge__$Vec_FlowsHarmonicTable$len(void* vec_ptr);
void* __swift_bridge__$Vec_FlowsHarmonicTable$as_ptr(void* vec_ptr);

double __swift_bridge__$flows_climate_south_anchor(void);
double __swift_bridge__$flows_climate_north_anchor(void);
double __swift_bridge__$flows_climate_pitch_degrees(void);
double __swift_bridge__$flows_climate_min_latitude(void);
double __swift_bridge__$flows_climate_max_latitude(void);
double __swift_bridge__$flows_climate_reference_elevation_meters(void);
double __swift_bridge__$flows_climate_meters_per_band_step(void);
struct __swift_bridge__$FlowsClimateOptional __swift_bridge__$flows_climate_band_index(double latitude);
int64_t __swift_bridge__$flows_climate_elevation_band_shift(double elevation_meters, bool has_elevation);
struct __swift_bridge__$FlowsClimateProfile __swift_bridge__$flows_climate_band_profile(double latitude, double elevation_meters, bool has_elevation);
void* __swift_bridge__$flows_climate_type_names(void);
struct __swift_bridge__$FlowsClimateProfile __swift_bridge__$flows_climate_type_profile(uint8_t code);
uint8_t __swift_bridge__$flows_climate_classify(double latitude, double longitude, double elevation_meters, bool has_elevation);
double __swift_bridge__$flows_climate_temp_sigma_f(void);
struct __swift_bridge__$FlowsClimateNorms __swift_bridge__$flows_climate_seasonal_norms(int64_t week, double latitude, double longitude, double elevation_meters, bool has_elevation);
bool __swift_bridge__$flows_climate_temperature_beyond_normal(double temp_f, double week_low_f, double week_high_f, double wind_mean_mph, double wind_sigma_mph);
bool __swift_bridge__$flows_climate_wind_beyond_normal(double wind_mph, double week_low_f, double week_high_f, double wind_mean_mph, double wind_sigma_mph);
struct __swift_bridge__$FlowsClimateProfile __swift_bridge__$flows_climate_profile(double latitude, double longitude, double elevation_meters, bool has_elevation);
double __swift_bridge__$flows_climate_civil_twilight_degrees(void);
double __swift_bridge__$flows_climate_julian_day(double now);
double __swift_bridge__$flows_climate_midnight_jd(double jd);
struct __swift_bridge__$FlowsClimateSolarTerms __swift_bridge__$flows_climate_solar_terms(double jd);
double __swift_bridge__$flows_climate_hour_angle_minutes(double latitude, double declination, double angle);
struct __swift_bridge__$FlowsClimateTwilight __swift_bridge__$flows_climate_twilight(double latitude, double longitude, double now, double angle);
bool __swift_bridge__$flows_climate_is_night(double latitude, double longitude, double now);
double __swift_bridge__$flows_climate_solar_elevation(double latitude, double longitude, double now);
double __swift_bridge__$flows_climate_next_change(double latitude, double longitude, double now);
double __swift_bridge__$flows_climate_score_max(void);
struct __swift_bridge__$FlowsClimateWeekTrig __swift_bridge__$flows_climate_week_trig(int64_t week);
bool __swift_bridge__$flows_climate_is_active(double expires, bool has_expires, double arrival_offset, double now);
int64_t __swift_bridge__$flows_climate_max_arrival_samples(void);
void* __swift_bridge__$flows_climate_arrival_offsets(int64_t sample_count, double total_travel_seconds);
void* __swift_bridge__$flows_climate_parse_flhh(struct __private__FfiSlice data);
void* __swift_bridge__$FlowsHarmonicTable$families(void* self);
void* __swift_bridge__$FlowsHarmonicTable$zips(void* self);
uint32_t __swift_bridge__$FlowsHarmonicTable$family_count(void* self);
int32_t __swift_bridge__$FlowsHarmonicTable$zip_index(void* self, struct RustStr zip);
struct __swift_bridge__$FlowsClimateOptional __swift_bridge__$FlowsHarmonicTable$score_named(void* self, struct RustStr zip, struct RustStr family, int64_t week);
double __swift_bridge__$FlowsHarmonicTable$score_row(void* self, int64_t zip_index, int64_t family_index, double cos_t, double sin_t, double cos_2t, double sin_2t);


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
double __swift_bridge__$flows_risk_green_min(void);
double __swift_bridge__$flows_risk_yellow_min(void);
double __swift_bridge__$flows_risk_red_min(void);
double __swift_bridge__$flows_secondary_ceiling(void);
double __swift_bridge__$flows_acute_nudge(void);
void* __swift_bridge__$flows_primary_families(void);
void* __swift_bridge__$flows_secondary_families(void);
void* __swift_bridge__$flows_acute_families(void);
void* __swift_bridge__$flows_weighted_family_names(void);
void* __swift_bridge__$flows_weighted_family_values(void);
uint8_t __swift_bridge__$flows_risk_band_code(double score);
double __swift_bridge__$flows_piecewise_score(double value, double low, double medium, double high);
double __swift_bridge__$flows_temperature_risk(double temp_f, double comfort_low_f, double comfort_high_f, double record_low_f, double record_high_f);
bool __swift_bridge__$flows_temperature_anomalous(double temp_f, double comfort_low_f, double comfort_high_f, double record_low_f, double record_high_f);
double __swift_bridge__$flows_wind_risk(double mph);
double __swift_bridge__$flows_pop_risk(double pct);
double __swift_bridge__$flows_forecast_composite(double temp, double wind, double pop);
double __swift_bridge__$flows_noisy_or_named(struct RustStr names, struct __private__FfiSlice scores);
double __swift_bridge__$flows_realized_risk_dense(struct __private__FfiSlice scores);
double __swift_bridge__$flows_flood_elevation_multiplier(double sample_elevation, bool has_sample_elevation, double local_min_elevation, bool has_local_min_elevation, double qpf_inches, bool has_qpf_inches, double supporting_evidence);
double __swift_bridge__$flows_ranking_risk(double band, double zip_exposure, double seasonal_prior, double prior_confidence);
int32_t __swift_bridge__$flows_alert_family_index(struct RustStr event);
int32_t __swift_bridge__$flows_peak_family_position(struct RustStr names, struct __private__FfiSlice scores, double floor);
int32_t __swift_bridge__$flows_dominant_family_position(struct RustStr names, struct __private__FfiSlice scores, double floor);
double __swift_bridge__$flows_displayed_band(double weighted, double peak);
void* __swift_bridge__$flows_decode_polyline_lonlat(struct __private__FfiSlice bytes);


// File automatically generated by swift-bridge.


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
typedef struct __swift_bridge__$TripVehicleOptional { double is_some; double value; } __swift_bridge__$TripVehicleOptional;
typedef struct __swift_bridge__$Option$TripVehicleOptional { bool is_some; __swift_bridge__$TripVehicleOptional val; } __swift_bridge__$Option$TripVehicleOptional;
typedef struct __swift_bridge__$TripVehicleHosStatus { double code; double seconds_until_due; } __swift_bridge__$TripVehicleHosStatus;
typedef struct __swift_bridge__$Option$TripVehicleHosStatus { bool is_some; __swift_bridge__$TripVehicleHosStatus val; } __swift_bridge__$Option$TripVehicleHosStatus;
typedef struct __swift_bridge__$TripVehicleHabits { double miles_since_fill; double average_speed_mph; double idle_fraction; } __swift_bridge__$TripVehicleHabits;
typedef struct __swift_bridge__$Option$TripVehicleHabits { bool is_some; __swift_bridge__$TripVehicleHabits val; } __swift_bridge__$Option$TripVehicleHabits;
typedef struct __swift_bridge__$TripVehicleClassPhysical { double tank; double height; double gvwr; double tow_capacity; } __swift_bridge__$TripVehicleClassPhysical;
typedef struct __swift_bridge__$Option$TripVehicleClassPhysical { bool is_some; __swift_bridge__$TripVehicleClassPhysical val; } __swift_bridge__$Option$TripVehicleClassPhysical;
void* __swift_bridge__$flows_trip_vehicle_fuel_type_names(void);
void* __swift_bridge__$flows_trip_vehicle_food_category_names(void);
void* __swift_bridge__$flows_trip_vehicle_need_label(uint8_t code);
double __swift_bridge__$flows_trip_vehicle_default_miles_per_unit(void);
uint8_t __swift_bridge__$flows_trip_vehicle_default_fuel_code(void);
double __swift_bridge__$flows_trip_vehicle_grams_co2_per_unit(uint8_t fuel);
double __swift_bridge__$flows_trip_vehicle_transit_grams_co2_per_mile(bool rail, bool long_haul);
struct __swift_bridge__$TripVehicleOptional __swift_bridge__$flows_trip_vehicle_drive_fuel_cost_usd(double miles, double miles_per_unit, double price_per_unit);
struct __swift_bridge__$TripVehicleOptional __swift_bridge__$flows_trip_vehicle_drive_grams_co2_per_mile(uint8_t fuel, double miles_per_unit);
void* __swift_bridge__$flows_trip_vehicle_schedule(double total_miles, struct __private__FfiSlice intervals, uint64_t seed);
int32_t __swift_bridge__$flows_trip_vehicle_next_need_index(double after_mile, struct __private__FfiSlice miles);
double __swift_bridge__$flows_trip_vehicle_adjusted_remaining_seconds(double baseline, double stop_delay_seconds);
uint64_t __swift_bridge__$flows_trip_vehicle_splitmix64_initial_state(uint64_t seed);
uint64_t __swift_bridge__$flows_trip_vehicle_splitmix64_advance(uint64_t state);
uint64_t __swift_bridge__$flows_trip_vehicle_splitmix64_mix(uint64_t state);
double __swift_bridge__$flows_trip_vehicle_impact_g_force(void);
double __swift_bridge__$flows_trip_vehicle_hard_impact_g_force(void);
double __swift_bridge__$flows_trip_vehicle_confirm_impact_g_force(void);
double __swift_bridge__$flows_trip_vehicle_min_pre_impact_speed_mps(void);
double __swift_bridge__$flows_trip_vehicle_crash_stop_speed_mps(void);
double __swift_bridge__$flows_trip_vehicle_min_speed_drop_fraction(void);
double __swift_bridge__$flows_trip_vehicle_max_meters_from_road(void);
void* __swift_bridge__$flows_trip_vehicle_assist_words(void);
void* __swift_bridge__$flows_trip_vehicle_ok_words(void);
bool __swift_bridge__$flows_trip_vehicle_is_impact_acceleration(double acceleration_g);
bool __swift_bridge__$flows_trip_vehicle_is_impact_window(struct __private__FfiSlice window);
bool __swift_bridge__$flows_trip_vehicle_is_crash(struct __private__FfiSlice window, double speed_before_mps, double speed_after_mps, double meters_from_road, bool has_meters_from_road);
int32_t __swift_bridge__$flows_trip_vehicle_interpret_reply(struct RustStr transcript);
double __swift_bridge__$flows_trip_vehicle_hos_break_due_seconds(void);
double __swift_bridge__$flows_trip_vehicle_hos_warn_before_break_seconds(void);
double __swift_bridge__$flows_trip_vehicle_hos_daily_driving_limit_seconds(void);
double __swift_bridge__$flows_trip_vehicle_hos_break_reset_seconds(void);
struct __swift_bridge__$TripVehicleHosStatus __swift_bridge__$flows_trip_vehicle_hos_status(double driving_seconds);
uint32_t __swift_bridge__$flows_trip_vehicle_spec_number_slots(void);
void* __swift_bridge__$flows_trip_vehicle_spec_makes(void);
void* __swift_bridge__$flows_trip_vehicle_spec_models(void);
void* __swift_bridge__$flows_trip_vehicle_spec_numbers(void);
void* __swift_bridge__$flows_trip_vehicle_distinct_makes(void);
void* __swift_bridge__$flows_trip_vehicle_spec_rows_for_make(struct RustStr make);
int32_t __swift_bridge__$flows_trip_vehicle_spec_index(struct RustStr make, struct RustStr model);
double __swift_bridge__$flows_trip_vehicle_minimum_height_feet(void);
double __swift_bridge__$flows_trip_vehicle_combined_miles_per_unit(double city_mpu, double highway_mpu);
double __swift_bridge__$flows_trip_vehicle_rated_miles_per_unit(double city_mpu, double highway_mpu);
double __swift_bridge__$flows_trip_vehicle_reserve_miles(void);
double __swift_bridge__$flows_trip_vehicle_efficiency_factor(double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_rated_range_miles(double tank_capacity_units, double rated_miles_per_unit);
double __swift_bridge__$flows_trip_vehicle_miles_per_unit_at_speed(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double mph);
double __swift_bridge__$flows_trip_vehicle_effective_range_miles(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_fuel_fraction_after(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double miles_since_fill, double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_expected_range_miles(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double miles_since_fill, double average_speed_mph, double idle_fraction);
bool __swift_bridge__$flows_trip_vehicle_should_recommend_fuel(double range_remaining_miles, double miles_to_next_station, double reserve_miles);
bool __swift_bridge__$flows_trip_vehicle_restore_driving_accepts(double average_speed_mph, double idle_fraction);
double __swift_bridge__$flows_trip_vehicle_restore_driving_idle(double idle_fraction);
struct __swift_bridge__$TripVehicleHabits __swift_bridge__$flows_trip_vehicle_record_fix(double miles_since_fill, double average_speed_mph, double idle_fraction, double speed_mps, double delta_meters, bool towing, double towing_economy_factor);
double __swift_bridge__$flows_trip_vehicle_store_expected_range_miles(double tank_capacity_units, double rated_miles_per_unit, double city_miles_per_unit, bool has_city_miles_per_unit, double highway_miles_per_unit, bool has_highway_miles_per_unit, double miles_since_fill, double average_speed_mph, double idle_fraction, double telemetry_fuel_fraction, bool has_telemetry_fuel_fraction, bool towing, double towing_economy_factor);
struct __swift_bridge__$TripVehicleClassPhysical __swift_bridge__$flows_trip_vehicle_epa_class_physical(struct RustStr vclass);
double __swift_bridge__$flows_trip_vehicle_epa_validated_tank(double tank, double combined_mpu);
uint8_t __swift_bridge__$flows_trip_vehicle_epa_fuel_type_code(struct RustStr fuel);


// File automatically generated by swift-bridge.
#include <stdint.h>
#include <stdbool.h>
double __swift_bridge__$flows_vehicle_policy_state_tolerance_mph(void);
double __swift_bridge__$flows_vehicle_policy_excess_over_limit_mph(void);
double __swift_bridge__$flows_vehicle_policy_excess_absolute_mph(void);
double __swift_bridge__$flows_vehicle_policy_speed_sign_tolerance_mph(void);
double __swift_bridge__$flows_vehicle_policy_speed_sign_over_by_mph(void);
double __swift_bridge__$flows_vehicle_policy_pursuit_default_speed_mph(void);
double __swift_bridge__$flows_vehicle_policy_pursuit_minimum_radius_meters(void);
double __swift_bridge__$flows_vehicle_policy_pursuit_maximum_elapsed_seconds(void);
double __swift_bridge__$flows_vehicle_policy_towing_economy_factor(void);
double __swift_bridge__$flows_vehicle_policy_filter_default_vehicle_height_meters(void);
double __swift_bridge__$flows_vehicle_policy_filter_default_max_grade_percent(void);
double __swift_bridge__$flows_vehicle_policy_filter_default_clearance_margin_meters(void);
double __swift_bridge__$flows_vehicle_policy_grade_steep_threshold_percent(void);
double __swift_bridge__$flows_vehicle_policy_grade_lookahead_miles(void);
double __swift_bridge__$flows_vehicle_policy_drive_idle_speed_mph(void);
double __swift_bridge__$flows_vehicle_policy_drive_default_efficient_cruise_mph(void);
void* __swift_bridge__$flows_vehicle_policy_compass_points(void);
double __swift_bridge__$flows_vehicle_policy_estimated_limit_mph(double speed_mph);
double __swift_bridge__$flows_vehicle_policy_effective_limit_mph(double posted_limit_mph, bool has_posted_limit_mph, double speed_mph);
double __swift_bridge__$flows_vehicle_policy_state_threshold_mph(double posted_limit_mph, bool has_posted_limit_mph);
double __swift_bridge__$flows_vehicle_policy_federal_threshold_mph(double posted_limit_mph, bool has_posted_limit_mph);
uint8_t __swift_bridge__$flows_vehicle_policy_standing_code(double speed_mph, double posted_limit_mph, bool has_posted_limit_mph);
int32_t __swift_bridge__$flows_vehicle_policy_compass_point_index(struct RustStr word);
double __swift_bridge__$flows_vehicle_policy_parse_maxspeed_mph(struct RustStr raw);
uint8_t __swift_bridge__$flows_vehicle_policy_judge_code(double speed_mph, double limit_mph, bool has_limit_mph);
double __swift_bridge__$flows_vehicle_policy_pursuit_radius_meters(double elapsed_seconds, double speed_mph);
void* __swift_bridge__$flows_vehicle_policy_towing_estimated_ratings(double height_feet, uint8_t fuel_code);
bool __swift_bridge__$flows_vehicle_policy_towing_has_effective_gcwr(bool has_gvwr_lbs, bool has_tow_capacity_lbs, bool has_gcwr_lbs);
double __swift_bridge__$flows_vehicle_policy_towing_effective_gcwr_lbs(double gvwr_lbs, bool has_gvwr_lbs, double tow_capacity_lbs, bool has_tow_capacity_lbs, double gcwr_lbs, bool has_gcwr_lbs);
void* __swift_bridge__$flows_vehicle_policy_towing_check(double vehicle_weight_lbs, double towed_weight_lbs, double gvwr_lbs, bool has_gvwr_lbs, double tow_capacity_lbs, bool has_tow_capacity_lbs, double gcwr_lbs, bool has_gcwr_lbs);
double __swift_bridge__$flows_vehicle_policy_degrees_to_percent(double degrees);
bool __swift_bridge__$flows_vehicle_policy_passes_clearances(double vehicle_height_meters, double clearance_margin_meters, struct __private__FfiSlice clearances_meters);
bool __swift_bridge__$flows_vehicle_policy_passes_grade(double max_grade_percent, double route_max_grade_percent, bool has_route_max_grade_percent);
bool __swift_bridge__$flows_vehicle_policy_passes_weight_limits(double rig_weight_lbs, bool has_rig_weight_lbs, struct __private__FfiSlice limits_lbs);
double __swift_bridge__$flows_vehicle_policy_default_max_grade_degrees(double published_max_grade_percent, bool has_published_max_grade_percent, double gvwr_lbs, bool has_gvwr_lbs, double tow_capacity_lbs, bool has_tow_capacity_lbs, double height_feet, bool towing, double trailer_weight_lbs);
void* __swift_bridge__$flows_vehicle_policy_grade_segments(struct __private__FfiSlice elevations, struct __private__FfiSlice present, double spacing_meters, double start_mile);
void* __swift_bridge__$flows_vehicle_policy_grade_steepest(struct __private__FfiSlice segments, int64_t top);
int64_t __swift_bridge__$flows_vehicle_policy_grade_next_steep_index(double mile, struct __private__FfiSlice segments, double threshold_percent, double lookahead_miles);
double __swift_bridge__$flows_vehicle_policy_drive_drag_penalty(double speed_mph, double efficient_cruise_mph);
double __swift_bridge__$flows_vehicle_policy_drive_grade_penalty(double grade_percent);
double __swift_bridge__$flows_vehicle_policy_drive_throttle_penalty(double accel_mph_per_sec);
double __swift_bridge__$flows_vehicle_policy_drive_headwind_mph(double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees);
double __swift_bridge__$flows_vehicle_policy_drive_airspeed_mph(double speed_mph, double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees);
double __swift_bridge__$flows_vehicle_policy_drive_drag_sensitivity(double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu);
double __swift_bridge__$flows_vehicle_policy_drive_load_factor(double loaded_weight_lbs, bool has_loaded_weight_lbs, double vehicle_weight_lbs, bool has_vehicle_weight_lbs, bool towing, double fuel_fraction, bool has_fuel_fraction);
double __swift_bridge__$flows_vehicle_policy_drive_score(double speed_mph, double accel_mph_per_sec, double grade_percent, double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees, double efficient_cruise_mph, double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu, double loaded_weight_lbs, bool has_loaded_weight_lbs, double vehicle_weight_lbs, bool has_vehicle_weight_lbs, bool towing, double fuel_fraction, bool has_fuel_fraction);
uint8_t __swift_bridge__$flows_vehicle_policy_drive_verdict_code(double speed_mph, double accel_mph_per_sec, double grade_percent, double wind_mph, double wind_from_degrees, bool has_wind_from_degrees, double heading_degrees, bool has_heading_degrees, double efficient_cruise_mph, double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu, double loaded_weight_lbs, bool has_loaded_weight_lbs, double vehicle_weight_lbs, bool has_vehicle_weight_lbs, bool towing, double fuel_fraction, bool has_fuel_fraction);
double __swift_bridge__$flows_vehicle_policy_drive_efficient_cruise_mph(double city_mpu, bool has_city_mpu, double highway_mpu, bool has_highway_mpu);


