// -----------------------------------------------------------------------------
// Copyright (c) 2026 David B. Foster. All rights reserved.
// Contact: wizeman555@gmail.com
// Unauthorized copying, distribution, modification, or use of this file, in
// whole or in part, is strictly prohibited without the express written
// permission of the copyright holder.
// -----------------------------------------------------------------------------

//! The airports airlines actually fly to, and which one a traveller would
//! drive to.
//!
//! The plane card used to ask a live map search "is there an airport near
//! here?" and turn any empty or throttled answer into "No flight fits this
//! trip" — for Milwaukee → Augusta, where both ends have daily service. It
//! also judged airports by NAME, which rejected real commercial fields whose
//! names carry a military word and accepted private strips.
//!
//! The table ([`crate::airports_table::AIRPORTS`], generated by
//! `flows-train`'s `airports-table` from OurAirports' public-domain data)
//! answers offline and knows the one thing a map search cannot: whether an
//! airport has SCHEDULED SERVICE.
//!
//! | here | used by |
//! |---|---|
//! | [`nearest`] | `Airports.nearest(to:)` behind the plane card's ends |
//! | [`pair`] | the plane card's "can this trip fly at all" check |
//!
//! Nothing here performs I/O and nothing allocates per airport: the table is
//! static, and a query walks it once.

use crate::geo;

/// How big an airport is — the tie-break when two are equally close. A
/// large airport is worth a longer drive than a small one.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Size {
    Large,
    Medium,
    Small,
}

impl Size {
    /// How much farther a traveller would reasonably drive for this size,
    /// as a multiplier on the straight-line distance when ranking. A large
    /// airport 60 miles away beats a small one 40 miles away.
    #[must_use]
    pub fn reach_bonus(self) -> f64 {
        match self {
            Size::Large => 0.55,
            Size::Medium => 0.85,
            Size::Small => 1.0,
        }
    }
}

/// One airport with scheduled airline service.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Airport {
    /// Three-letter IATA code ("MKE"), what a booking site wants.
    pub iata: &'static str,
    /// "Milwaukee Mitchell International Airport".
    pub name: &'static str,
    /// "Milwaukee" — the city it serves, which is how people name it.
    pub city: &'static str,
    /// "US", "CA" or "MX".
    pub country: &'static str,
    /// "US-WI" — the state or province, which a rental landing page is
    /// named for.
    pub region: &'static str,
    pub lat: f64,
    pub lon: f64,
    pub size: Size,
}

/// How far a traveller will drive to an airport before flying stops making
/// sense (straight-line meters). Past this, the plane card has no end.
pub const MAX_DRIVE_METERS: f64 = 240_000.0; // ~150 miles

/// And never more than this share of the trip itself: driving 100 miles to
/// fly 150 is not a trip anybody takes.
pub const MAX_DRIVE_SHARE_OF_TRIP: f64 = 0.4;

/// The airports near a point, best first: ranked by distance weighted by
/// size ([`Size::reach_bonus`]), and never past `max_meters`.
///
/// Deterministic; allocates the answer; panics: none.
#[must_use]
pub fn nearest(lat: f64, lon: f64, limit: usize, max_meters: f64) -> Vec<&'static Airport> {
    if limit == 0 || !lat.is_finite() || !lon.is_finite() {
        return Vec::new();
    }
    let mut scored: Vec<(f64, &'static Airport)> = crate::airports_table::AIRPORTS
        .iter()
        .filter_map(|a| {
            let meters = geo::meters(lat, lon, a.lat, a.lon);
            (meters <= max_meters).then_some((meters * a.size.reach_bonus(), a))
        })
        .collect();
    // Stable order for equal scores: the table is sorted by code, so two
    // airports the same weighted distance away always come back the same way.
    scored.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));
    scored.truncate(limit);
    scored.into_iter().map(|(_, a)| a).collect()
}

/// The airport with this IATA code.
#[must_use]
pub fn code(iata: &str) -> Option<&'static Airport> {
    let want = iata.trim().to_ascii_uppercase();
    crate::airports_table::AIRPORTS
        .binary_search_by(|a| a.iata.cmp(want.as_str()))
        .ok()
        .and_then(|i| crate::airports_table::AIRPORTS.get(i))
}

/// The ends of a flight for a trip: the best airport near each end, or
/// `None` when either end has no airport within driving reach or the two
/// resolve to the same airport (nobody flies from an airport to itself).
///
/// `min_gap_meters`: how far apart the airports must be for flying to be
/// worth the airport time at all.
///
/// A trip shorter than that gap has no flight, whatever airports sit near
/// its ends — and the drive to an airport is held to a share of the trip, so
/// a Milwaukee-to-Madison hop is never "flown" out of Chicago.
#[must_use]
pub fn pair(
    from: (f64, f64),
    to: (f64, f64),
    max_drive_meters: f64,
    min_gap_meters: f64,
) -> Option<(&'static Airport, &'static Airport)> {
    let trip = geo::meters(from.0, from.1, to.0, to.1);
    if trip < min_gap_meters {
        return None;
    }
    let reach = max_drive_meters.min(trip * MAX_DRIVE_SHARE_OF_TRIP);
    let board = nearest(from.0, from.1, 4, reach);
    let alight = nearest(to.0, to.1, 4, reach);
    let first_board = *board.first()?;
    let first_alight = *alight.first()?;
    // The usual case: two different airports, far enough apart.
    if first_board.iata != first_alight.iata
        && geo::meters(
            first_board.lat,
            first_board.lon,
            first_alight.lat,
            first_alight.lon,
        ) >= min_gap_meters
    {
        return Some((first_board, first_alight));
    }
    // They share an airport (or sit too close): try the next-best arrival,
    // then the next-best departure, before giving up. A short hop between
    // neighbouring cities has no flight, and saying so is the honest answer.
    for b in &board {
        for a in &alight {
            if b.iata != a.iata && geo::meters(b.lat, b.lon, a.lat, a.lon) >= min_gap_meters {
                return Some((b, a));
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    const MILWAUKEE: (f64, f64) = (43.0389, -87.9065);
    const EVANS_GA: (f64, f64) = (33.5337, -82.1307); // the owner's trip
    const MADISON: (f64, f64) = (43.0731, -89.4012);

    #[test]
    fn the_table_is_sorted_and_plausible() {
        let table = crate::airports_table::AIRPORTS;
        assert!(table.len() > 400, "{} airports", table.len());
        for pair in table.windows(2) {
            assert!(pair[0].iata < pair[1].iata, "sorted, one row per code");
        }
        for a in table {
            assert_eq!(a.iata.len(), 3);
            assert!((-90.0..=90.0).contains(&a.lat) && (-180.0..=180.0).contains(&a.lon));
            assert!(["US", "CA", "MX"].contains(&a.country));
        }
    }

    #[test]
    fn the_owners_trip_has_two_airports() {
        // Milwaukee → Evans, Georgia: MKE at one end, AGS (Augusta) at the
        // other. The map-search path answered "No flight fits this trip".
        let (board, alight) =
            pair(MILWAUKEE, EVANS_GA, MAX_DRIVE_METERS, 100_000.0).expect("a flight fits");
        assert_eq!(board.iata, "MKE");
        assert_eq!(alight.iata, "AGS");
        assert_eq!(alight.city, "Augusta");
    }

    #[test]
    fn a_big_airport_is_worth_a_longer_drive() {
        // From Madison: MSN is closest, but Chicago and Milwaukee are the
        // ones with the flights — all three must be offered, MSN first.
        let near = nearest(MADISON.0, MADISON.1, 4, MAX_DRIVE_METERS);
        let codes: Vec<&str> = near.iter().map(|a| a.iata).collect();
        assert_eq!(codes.first(), Some(&"MSN"), "{codes:?}");
        assert!(
            codes.contains(&"MKE") || codes.contains(&"ORD"),
            "{codes:?}"
        );
    }

    #[test]
    fn a_short_hop_has_no_flight() {
        // Milwaukee to Madison is 80 miles: no airport pair clears the gap.
        assert!(pair(MILWAUKEE, MADISON, MAX_DRIVE_METERS, 160_000.0).is_none());
    }

    #[test]
    fn nowhere_near_an_airport_answers_nothing() {
        // The middle of the Pacific.
        assert!(nearest(0.0, -160.0, 3, MAX_DRIVE_METERS).is_empty());
        assert!(pair((0.0, -160.0), MILWAUKEE, MAX_DRIVE_METERS, 100_000.0).is_none());
        assert!(nearest(f64::NAN, 0.0, 3, MAX_DRIVE_METERS).is_empty());
        assert!(nearest(43.0, -89.0, 0, MAX_DRIVE_METERS).is_empty());
    }

    #[test]
    fn a_code_resolves_both_ways() {
        let mke = code("mke").expect("MKE");
        assert_eq!(mke.city, "Milwaukee");
        assert!(code("ZZZ").is_none());
    }
}
